import { SYMBOL_MAP } from "../../symbols/index.js";
import { accentTemplate, overunderTemplate, scriptStackTemplate } from "../templates/index.js";

export const accentsMapping = {
    hat: (node, render) => accentTemplate(node, render, SYMBOL_MAP["hat"], false),
    check: (node, render) => accentTemplate(node, render, SYMBOL_MAP["check"], false),
    breve: (node, render) => accentTemplate(node, render, SYMBOL_MAP["breve"], false),
    acute: (node, render) => accentTemplate(node, render, SYMBOL_MAP["acute"], false),
    grave: (node, render) => accentTemplate(node, render, SYMBOL_MAP["grave"], false),
    tilde: (node, render) => accentTemplate(node, render, SYMBOL_MAP["tilde"], false),
    bar: (node, render) => accentTemplate(node, render, SYMBOL_MAP["bar"], false),
    vec: (node, render) => accentTemplate(node, render, SYMBOL_MAP["vec"], false),
    dot: (node, render) => accentTemplate(node, render, SYMBOL_MAP["dot"], false),
    ddot: (node, render) => accentTemplate(node, render, SYMBOL_MAP["ddot"], false),
    dddot: (node, render) => accentTemplate(node, render, SYMBOL_MAP["dddot"], false),
    ddddot: (node, render) => accentTemplate(node, render, SYMBOL_MAP["ddddot"], false),
    mathring: (node, render) => accentTemplate(node, render, SYMBOL_MAP["mathring"], false),
    widehat: (node, render) => accentTemplate(node, render, SYMBOL_MAP["widehat"], false),
    widetilde: (node, render) => accentTemplate(node, render, SYMBOL_MAP["widetilde"], false),
    widecheck: (node, render) => accentTemplate(node, render, SYMBOL_MAP["widecheck"], false),
    wideparen: (node, render) => accentTemplate(node, render, SYMBOL_MAP["wideparen"], false),
    overline: (node, render) => accentTemplate(node, render, SYMBOL_MAP["overline"], false),
    underline: (node, render) => accentTemplate(node, render, SYMBOL_MAP["underline"], true),
    overgroup: (node, render) => accentTemplate(node, render, SYMBOL_MAP["overgroup"], false),
    undergroup: (node, render) => accentTemplate(node, render, SYMBOL_MAP["undergroup"], true),
    overparen: (node, render) => accentTemplate(node, render, SYMBOL_MAP["overparen"], false),
    underparen: (node, render) => accentTemplate(node, render, SYMBOL_MAP["underparen"], true),
    overrightarrow: (node, render) => accentTemplate(node, render, SYMBOL_MAP["overrightarrow"], false),
    overleftarrow: (node, render) => accentTemplate(node, render, SYMBOL_MAP["overleftarrow"], false),
    overleftrightarrow: (node, render) => accentTemplate(node, render, SYMBOL_MAP["overleftrightarrow"], false),
    underrightarrow: (node, render) => accentTemplate(node, render, SYMBOL_MAP["underrightarrow"], true),
    underleftarrow: (node, render) => accentTemplate(node, render, SYMBOL_MAP["underleftarrow"], true),
    underleftrightarrow: (node, render) => accentTemplate(node, render, SYMBOL_MAP["underleftrightarrow"], true),
    utilde: (node, render) => accentTemplate(node, render, SYMBOL_MAP["utilde"], true),
    overbrace: (node, render) => overunderTemplate(node, render, SYMBOL_MAP["overbrace"], false),
    underbrace: (node, render) => overunderTemplate(node, render, SYMBOL_MAP["underbrace"], true),
    overset: (node, render) => scriptStackTemplate(node, render, false),
    underset: (node, render) => scriptStackTemplate(node, render, true),
    stackrel: (node, render) => scriptStackTemplate(node, render, false),
};
