export const COMMANDS = Object.freeze({
    ["frac"]: { args: 2, optArgs: 0 },
    ["dfrac"]: { args: 2, optArgs: 0 },
    ["tfrac"]: { args: 2, optArgs: 0 },
    ["cfrac"]: { args: 2, optArgs: 0 },
    ["sqrt"]: { args: 1, optArgs: 1 },

    ["binom"]: { args: 2, optArgs: 0 },
    ["dbinom"]: { args: 2, optArgs: 0 },
    ["tbinom"]: { args: 2, optArgs: 0 },

    ["hat"]: { args: 1, optArgs: 0 },
    ["check"]: { args: 1, optArgs: 0 },
    ["breve"]: { args: 1, optArgs: 0 },
    ["acute"]: { args: 1, optArgs: 0 },
    ["grave"]: { args: 1, optArgs: 0 },
    ["tilde"]: { args: 1, optArgs: 0 },
    ["bar"]: { args: 1, optArgs: 0 },
    ["vec"]: { args: 1, optArgs: 0 },
    ["dot"]: { args: 1, optArgs: 0 },
    ["ddot"]: { args: 1, optArgs: 0 },
    ["widehat"]: { args: 1, optArgs: 0 },
    ["widetilde"]: { args: 1, optArgs: 0 },
    ["overline"]: { args: 1, optArgs: 0 },
    ["underline"]: { args: 1, optArgs: 0 },
    ["overbrace"]: { args: 1, optArgs: 0 },
    ["underbrace"]: { args: 1, optArgs: 0 },

    ["mathrm"]: { args: 1, optArgs: 0 },
    ["mathbf"]: { args: 1, optArgs: 0 },
    ["mathit"]: { args: 1, optArgs: 0 },
    ["mathbb"]: { args: 1, optArgs: 0 },
    ["mathcal"]: { args: 1, optArgs: 0 },
    ["mathfrak"]: { args: 1, optArgs: 0 },
    ["mathsf"]: { args: 1, optArgs: 0 },
    ["mathtt"]: { args: 1, optArgs: 0 },
    ["text"]: { args: 1, optArgs: 0 },
    ["mbox"]: { args: 1, optArgs: 0 },

    ["overset"]: { args: 2, optArgs: 0 },
    ["underset"]: { args: 2, optArgs: 0 },
    ["stackrel"]: { args: 2, optArgs: 0 },
    ["xrightarrow"]: { args: 1, optArgs: 1 },
    ["xleftarrow"]: { args: 1, optArgs: 1 },
    ["xLeftarrow"]: { args: 1, optArgs: 1 },
    ["xRightarrow"]: { args: 1, optArgs: 1 },

    ["quad"]: { args: 0, optArgs: 0 },
    ["qquad"]: { args: 0, optArgs: 0 },
    ["hspace"]: { args: 1, optArgs: 0 },
    ["vspace"]: { args: 1, optArgs: 0 },

    ["alpha"]: { args: 0, optArgs: 0 },
    ["beta"]: { args: 0, optArgs: 0 },
    ["gamma"]: { args: 0, optArgs: 0 },
    ["delta"]: { args: 0, optArgs: 0 },
    ["epsilon"]: { args: 0, optArgs: 0 },
    ["varepsilon"]: { args: 0, optArgs: 0 },
    ["zeta"]: { args: 0, optArgs: 0 },
    ["eta"]: { args: 0, optArgs: 0 },
    ["theta"]: { args: 0, optArgs: 0 },
    ["vartheta"]: { args: 0, optArgs: 0 },
    ["iota"]: { args: 0, optArgs: 0 },
    ["kappa"]: { args: 0, optArgs: 0 },
    ["lambda"]: { args: 0, optArgs: 0 },
    ["mu"]: { args: 0, optArgs: 0 },
    ["nu"]: { args: 0, optArgs: 0 },
    ["xi"]: { args: 0, optArgs: 0 },
    ["pi"]: { args: 0, optArgs: 0 },
    ["varpi"]: { args: 0, optArgs: 0 },
    ["rho"]: { args: 0, optArgs: 0 },
    ["varrho"]: { args: 0, optArgs: 0 },
    ["sigma"]: { args: 0, optArgs: 0 },
    ["varsigma"]: { args: 0, optArgs: 0 },
    ["tau"]: { args: 0, optArgs: 0 },
    ["upsilon"]: { args: 0, optArgs: 0 },
    ["phi"]: { args: 0, optArgs: 0 },
    ["varphi"]: { args: 0, optArgs: 0 },
    ["chi"]: { args: 0, optArgs: 0 },
    ["psi"]: { args: 0, optArgs: 0 },
    ["omega"]: { args: 0, optArgs: 0 },

    ["Alpha"]: { args: 0, optArgs: 0 },
    ["Beta"]: { args: 0, optArgs: 0 },
    ["Gamma"]: { args: 0, optArgs: 0 },
    ["Delta"]: { args: 0, optArgs: 0 },
    ["Epsilon"]: { args: 0, optArgs: 0 },
    ["Zeta"]: { args: 0, optArgs: 0 },
    ["Eta"]: { args: 0, optArgs: 0 },
    ["Theta"]: { args: 0, optArgs: 0 },
    ["Iota"]: { args: 0, optArgs: 0 },
    ["Kappa"]: { args: 0, optArgs: 0 },
    ["Lambda"]: { args: 0, optArgs: 0 },
    ["Mu"]: { args: 0, optArgs: 0 },
    ["Nu"]: { args: 0, optArgs: 0 },
    ["Xi"]: { args: 0, optArgs: 0 },
    ["Pi"]: { args: 0, optArgs: 0 },
    ["Rho"]: { args: 0, optArgs: 0 },
    ["Sigma"]: { args: 0, optArgs: 0 },
    ["Tau"]: { args: 0, optArgs: 0 },
    ["Upsilon"]: { args: 0, optArgs: 0 },
    ["Phi"]: { args: 0, optArgs: 0 },
    ["Chi"]: { args: 0, optArgs: 0 },
    ["Psi"]: { args: 0, optArgs: 0 },
    ["Omega"]: { args: 0, optArgs: 0 },

    ["pm"]: { args: 0, optArgs: 0 },
    ["mp"]: { args: 0, optArgs: 0 },
    ["times"]: { args: 0, optArgs: 0 },
    ["div"]: { args: 0, optArgs: 0 },
    ["cdot"]: { args: 0, optArgs: 0 },
    ["ast"]: { args: 0, optArgs: 0 },
    ["star"]: { args: 0, optArgs: 0 },
    ["circ"]: { args: 0, optArgs: 0 },
    ["bullet"]: { args: 0, optArgs: 0 },
    ["oplus"]: { args: 0, optArgs: 0 },
    ["ominus"]: { args: 0, optArgs: 0 },
    ["otimes"]: { args: 0, optArgs: 0 },
    ["oslash"]: { args: 0, optArgs: 0 },
    ["wedge"]: { args: 0, optArgs: 0 },
    ["vee"]: { args: 0, optArgs: 0 },
    ["cap"]: { args: 0, optArgs: 0 },
    ["cup"]: { args: 0, optArgs: 0 },
    ["setminus"]: { args: 0, optArgs: 0 },

    ["leq"]: { args: 0, optArgs: 0 },
    ["geq"]: { args: 0, optArgs: 0 },
    ["neq"]: { args: 0, optArgs: 0 },
    ["approx"]: { args: 0, optArgs: 0 },
    ["sim"]: { args: 0, optArgs: 0 },
    ["simeq"]: { args: 0, optArgs: 0 },
    ["equiv"]: { args: 0, optArgs: 0 },
    ["cong"]: { args: 0, optArgs: 0 },
    ["subset"]: { args: 0, optArgs: 0 },
    ["supset"]: { args: 0, optArgs: 0 },
    ["subseteq"]: { args: 0, optArgs: 0 },
    ["supseteq"]: { args: 0, optArgs: 0 },
    ["in"]: { args: 0, optArgs: 0 },
    ["notin"]: { args: 0, optArgs: 0 },
    ["ni"]: { args: 0, optArgs: 0 },
    ["propto"]: { args: 0, optArgs: 0 },
    ["perp"]: { args: 0, optArgs: 0 },
    ["mid"]: { args: 0, optArgs: 0 },
    ["parallel"]: { args: 0, optArgs: 0 },

    ["rightarrow"]: { args: 0, optArgs: 0 },
    ["leftarrow"]: { args: 0, optArgs: 0 },
    ["Rightarrow"]: { args: 0, optArgs: 0 },
    ["Leftarrow"]: { args: 0, optArgs: 0 },
    ["leftrightarrow"]: { args: 0, optArgs: 0 },
    ["Leftrightarrow"]: { args: 0, optArgs: 0 },
    ["uparrow"]: { args: 0, optArgs: 0 },
    ["downarrow"]: { args: 0, optArgs: 0 },
    ["to"]: { args: 0, optArgs: 0 },
    ["gets"]: { args: 0, optArgs: 0 },
    ["mapsto"]: { args: 0, optArgs: 0 },
    ["hookrightarrow"]: { args: 0, optArgs: 0 },
    ["longrightarrow"]: { args: 0, optArgs: 0 },
    ["Longrightarrow"]: { args: 0, optArgs: 0 },
    ["longleftrightarrow"]: { args: 0, optArgs: 0 },

    ["sum"]: { args: 0, optArgs: 0 },
    ["prod"]: { args: 0, optArgs: 0 },
    ["coprod"]: { args: 0, optArgs: 0 },
    ["int"]: { args: 0, optArgs: 0 },
    ["iint"]: { args: 0, optArgs: 0 },
    ["iiint"]: { args: 0, optArgs: 0 },
    ["oint"]: { args: 0, optArgs: 0 },
    ["bigcup"]: { args: 0, optArgs: 0 },
    ["bigcap"]: { args: 0, optArgs: 0 },
    ["bigoplus"]: { args: 0, optArgs: 0 },
    ["bigotimes"]: { args: 0, optArgs: 0 },
    ["bigsqcup"]: { args: 0, optArgs: 0 },
    ["bigvee"]: { args: 0, optArgs: 0 },
    ["bigwedge"]: { args: 0, optArgs: 0 },
    ["lim"]: { args: 0, optArgs: 0 },
    ["max"]: { args: 0, optArgs: 0 },
    ["min"]: { args: 0, optArgs: 0 },
    ["sup"]: { args: 0, optArgs: 0 },
    ["inf"]: { args: 0, optArgs: 0 },

    ["infty"]: { args: 0, optArgs: 0 },
    ["partial"]: { args: 0, optArgs: 0 },
    ["nabla"]: { args: 0, optArgs: 0 },
    ["forall"]: { args: 0, optArgs: 0 },
    ["exists"]: { args: 0, optArgs: 0 },
    ["nexists"]: { args: 0, optArgs: 0 },
    ["emptyset"]: { args: 0, optArgs: 0 },
    ["varnothing"]: { args: 0, optArgs: 0 },
    ["ldots"]: { args: 0, optArgs: 0 },
    ["cdots"]: { args: 0, optArgs: 0 },
    ["vdots"]: { args: 0, optArgs: 0 },
    ["ddots"]: { args: 0, optArgs: 0 },
    ["aleph"]: { args: 0, optArgs: 0 },
    ["hbar"]: { args: 0, optArgs: 0 },
    ["ell"]: { args: 0, optArgs: 0 },
    ["Re"]: { args: 0, optArgs: 0 },
    ["Im"]: { args: 0, optArgs: 0 },
    ["wp"]: { args: 0, optArgs: 0 },
    ["prime"]: { args: 0, optArgs: 0 },

    ["left"]: { args: 0, optArgs: 0 },
    ["right"]: { args: 0, optArgs: 0 },
    ["langle"]: { args: 0, optArgs: 0 },
    ["rangle"]: { args: 0, optArgs: 0 },
    ["lfloor"]: { args: 0, optArgs: 0 },
    ["rfloor"]: { args: 0, optArgs: 0 },
    ["lceil"]: { args: 0, optArgs: 0 },
    ["rceil"]: { args: 0, optArgs: 0 },

    ["sin"]: { args: 0, optArgs: 0 },
    ["cos"]: { args: 0, optArgs: 0 },
    ["tan"]: { args: 0, optArgs: 0 },
    ["cot"]: { args: 0, optArgs: 0 },
    ["sec"]: { args: 0, optArgs: 0 },
    ["csc"]: { args: 0, optArgs: 0 },
    ["arcsin"]: { args: 0, optArgs: 0 },
    ["arccos"]: { args: 0, optArgs: 0 },
    ["arctan"]: { args: 0, optArgs: 0 },
    ["sinh"]: { args: 0, optArgs: 0 },
    ["cosh"]: { args: 0, optArgs: 0 },
    ["tanh"]: { args: 0, optArgs: 0 },
    ["log"]: { args: 0, optArgs: 0 },
    ["ln"]: { args: 0, optArgs: 0 },
    ["exp"]: { args: 0, optArgs: 0 },
    ["det"]: { args: 0, optArgs: 0 },
    ["deg"]: { args: 0, optArgs: 0 },
    ["gcd"]: { args: 0, optArgs: 0 },
    ["ker"]: { args: 0, optArgs: 0 },
    ["hom"]: { args: 0, optArgs: 0 },
    ["Pr"]: { args: 0, optArgs: 0 },
    ["arg"]: { args: 0, optArgs: 0 },
    ["dim"]: { args: 0, optArgs: 0 },

    ["displaystyle"]: { args: 0, optArgs: 0 },
    ["textstyle"]: { args: 0, optArgs: 0 },
    ["scriptstyle"]: { args: 0, optArgs: 0 },
    ["not"]: { args: 0, optArgs: 0 },

    // ["begin"]: { args: 1, optArgs: 0 },
    // ["end"]: { args: 1, optArgs: 0 },
    // ["\\"]: { args: 0, optArgs: 0 },
    // ["%"]: { args: 0, optArgs: 0 },
    // ["$"]: { args: 0, optArgs: 0 },
    // ["~"]: { args: 0, optArgs: 0 },
    // ["#"]: { args: 0, optArgs: 0 },
    // ["{"]: { args: 0, optArgs: 0 },
    // ["}"]: { args: 0, optArgs: 0 },
    // ["("]: { args: 0, optArgs: 0 },
    // [")"]: { args: 0, optArgs: 0 },
    // ["["]: { args: 0, optArgs: 0 },
    // ["]"]: { args: 0, optArgs: 0 },
    // ["^"]: { args: 0, optArgs: 0 },
    // ["_"]: { args: 0, optArgs: 0 },
    // ["+"]: { args: 0, optArgs: 0 },
    // ["-"]: { args: 0, optArgs: 0 },
    // ["*"]: { args: 0, optArgs: 0 },
    // ["/"]: { args: 0, optArgs: 0 },
    // ["="]: { args: 0, optArgs: 0 },
    // ["<"]: { args: 0, optArgs: 0 },
    // [">"]: { args: 0, optArgs: 0 },
    // ["|"]: { args: 0, optArgs: 0 },
    // [";"]: { args: 0, optArgs: 0 },
    // [":"]: { args: 0, optArgs: 0 },
    // [","]: { args: 0, optArgs: 0 },
    // ["!"]: { args: 0, optArgs: 0 },
    // ["?"]: { args: 0, optArgs: 0 },
});
