export const TOKEN_TYPE = Object.freeze({
    COMMAND: "COMMAND",
    NUMBER: "NUMBER",
    IDENTIFIER: "IDENTIFIER",
    LBRACE: "LBRACE",
    RBRACE: "RBRACE",
    LPAREN: "LPAREN",
    RPAREN: "RPAREN",
    LBRACKET: "LBRACKET",
    RBRACKET: "RBRACKET",
    SUP: "SUP",
    SUB: "SUB",
    OPERATOR: "OPERATOR",
    ALIGN: "ALIGN",
    SPACE: "SPACE",
    COMMENT: "COMMENT",
    DOLLAR: "DOLLAR",
    TILDE: "TILDE",
    CHAR: "CHAR",
});

export const NODE_TYPE = Object.freeze({
    ROOT: "ROOT",
    SEQUENCE: "SEQUENCE",
    GROUP: "GROUP",
    NUMBER: "NUMBER",
    IDENTIFIER: "IDENTIFIER",
    OPERATOR: "OPERATOR",
    SCRIPT: "SCRIPT",
    COMMAND: "COMMAND",
    ENVIRONMENT: "ENVIRONMENT",
    LEFTRIGHT: "LEFTRIGHT",
    STYLE: "STYLE",
    ERROR: "ERROR",
});

export const ALLOWED_DELIMITER_TYPES = Object.freeze(new Set([TOKEN_TYPE.OPERATOR, TOKEN_TYPE.IDENTIFIER, TOKEN_TYPE.COMMAND, TOKEN_TYPE.CHAR, TOKEN_TYPE.LPAREN, TOKEN_TYPE.RPAREN, TOKEN_TYPE.LBRACKET, TOKEN_TYPE.RBRACKET, TOKEN_TYPE.LBRACE, TOKEN_TYPE.RBRACE]));
