export const COMMAND_LATEX_MAP: Record<string, string | string[]> = {
    frac: ["\\frac{a + b}{c + d}", "\\frac{1}{1 + \\frac{1}{x}}", "\\displaystyle\\frac{1}{1 + x}", "\\textstyle\\frac{1}{1 + x}"],
    dfrac: "\\dfrac{\\partial^2 f}{\\partial x \\partial y}",
    tfrac: "\\tfrac{1}{2}mv^2 + \\tfrac{1}{2}kx^2",
    cfrac: "\\cfrac{1}{1 + \\cfrac{1}{1 + x}}",
    sfrac: "\\sfrac{a + b}{c + d}",
    nicefrac: "\\nicefrac{a + b}{c + d}",
    flatfrac: "\\flatfrac{a + b}{c + d}",
    sqrt: ["\\sqrt{x}", "\\sqrt{x^2 + y^2}", "\\sqrt[3]{x^3 + y^3}"],
    binom: ["\\binom{n}{k}", "\\displaystyle\\binom{n}{k}", "\\textstyle\\binom{n}{k}"],
    dbinom: "\\dbinom{n}{k}",
    tbinom: "\\tbinom{n}{k}",
    choose: "{n \\choose k} = \\frac{n!}{k!(n-k)!}",
    above: "{a + b \\above c + d}",
    atop: "{a + b \\atop c + d}",
    over: "{a + b \\over c + d}",
    hat: ["\\hat{x}", "\\hat{\\theta}"],
    check: "\\check{x}",
    breve: "\\breve{x}",
    acute: "\\acute{x}",
    grave: "\\grave{x}",
    tilde: "\\tilde{x}",
    bar: ["\\bar{x}", "\\bar{AB}"],
    vec: "\\vec{F} = m\\vec{a}",
    dot: "\\dot{x} = v",
    ddot: "\\ddot{x} = a",
    dddot: "\\dddot{x}",
    ddddot: "\\ddddot{x}",
    mathring: "\\mathring{x}",
    widehat: "\\widehat{ABC}",
    widetilde: "\\widetilde{A \\cup B}",
    widecheck: "\\widecheck{xyz}",
    wideparen: "\\wideparen{xyz}",
    overline: "\\overline{A \\cup B} = \\overline{A} \\cap \\overline{B}",
    underline: "\\underline{x_1 + x_2}",
    overbrace: "\\overbrace{x_1 + x_2 + \\cdots + x_n}^{S_n}",
    underbrace: "\\underbrace{1 + 2 + \\cdots + n}_{n\\text{ terms}}",
    overgroup: "\\overgroup{xyz}",
    undergroup: "\\undergroup{xyz}",
    overparen: "\\overparen{xyz}",
    underparen: "\\underparen{xyz}",
    overleftarrow: "\\overleftarrow{AB}",
    overrightarrow: "\\overrightarrow{AB} + \\overrightarrow{BC} = \\overrightarrow{AC}",
    overleftrightarrow: "\\overleftrightarrow{AB}",
    underleftarrow: "\\underleftarrow{AB}",
    underrightarrow: "\\underrightarrow{x_1 + x_2}",
    underleftrightarrow: "\\underleftrightarrow{x_1 + x_2}",
    utilde: "\\utilde{x}",
    overset: "x \\overset{\\text{def}}{=} y",
    underset: "\\underset{x \\to 0}{\\lim} \\frac{\\sin x}{x}",
    stackrel: "X_n \\stackrel{d}{\\longrightarrow} X",
    xrightarrow: ["A \\xrightarrow{f} B", "X \\xrightarrow[n \\to \\infty]{\\text{weak}} X_0"],
    xleftarrow: "A \\xleftarrow{f} B",
    xLeftarrow: "A \\xLeftarrow{\\text{proof}} B",
    xRightarrow: "A \\xRightarrow{\\text{implies}} B",
    xLeftrightarrow: "A \\xLeftrightarrow{\\text{iff}} B",
    xleftrightarrow: "A \\xleftrightarrow{\\sim} B",
    xhookleftarrow: "A \\xhookleftarrow{i} B",
    xhookrightarrow: "A \\xhookrightarrow{i} B",
    xmapsto: "x \\xmapsto{f} f(x)",
    xtwoheadleftarrow: "A \\xtwoheadleftarrow{p} B",
    xtwoheadrightarrow: "A \\xtwoheadrightarrow{p} B",
    xlongequal: "x \\xlongequal{\\text{def}} y",
    xrightharpoonup: "R \\xrightharpoonup{k_1} S",
    xrightharpoondown: "R \\xrightharpoondown{k_2} S",
    xleftharpoonup: "R \\xleftharpoonup{k_1} S",
    xleftharpoondown: "R \\xleftharpoondown{k_2} S",
    xrightleftharpoons: "R \\xrightleftharpoons[k_{-1}]{k_1} S",
    xleftrightharpoons: "R \\xleftrightharpoons[k_{-1}]{k_1} S",
    mathrm: "\\mathrm{d}x",
    mathbf: "\\mathbf{A}\\mathbf{x} = \\mathbf{b}",
    mathit: "\\mathit{x}",
    mathbb: "\\mathbb{R}^n \\to \\mathbb{R}^m",
    mathcal: "\\mathcal{O}(n \\log n)",
    mathfrak: "\\mathfrak{sl}_2(\\mathbb{C})",
    mathsf: "\\mathsf{x}",
    mathtt: "\\mathtt{x}",
    mathnormal: "\\mathnormal{x}",
    mathscr: "\\mathscr{F}\\{f\\}",
    mathbfit: "\\mathbfit{x}",
    mathsfit: "\\mathsfit{x}",
    mathbfsfit: "\\mathbfsfit{x}",
    boldsymbol: "\\boldsymbol{x}",
    bm: "\\bm{x}",
    pmb: "\\pmb{x}",
    text: "\\text{area} = \\pi r^2",
    mbox: "\\mbox{area} = \\pi r^2",
    textbf: "\\textbf{x}",
    textit: "\\textit{x}",
    textrm: "\\textrm{x}",
    textsf: "\\textsf{x}",
    texttt: "\\texttt{x}",
    textnormal: "\\textnormal{x}",
    textup: "\\textup{x}",
    scr: "\\scr{x}",
    cal: "\\cal{x}",
    Bbb: "\\Bbb{x}",
    frak: "\\frak{x}",
    rm: "\\rm{x}",
    bf: "\\bf{x}",
    it: "\\it{x}",
    sf: "\\sf{x}",
    tt: "\\tt{x}",
    quad: "a\\quad b",
    qquad: "a\\qquad b",
    thinspace: "a\\thinspace b",
    medspace: "a\\medspace b",
    thickspace: "a\\thickspace b",
    negthinspace: "a\\negthinspace b",
    negmedspace: "a\\negmedspace b",
    negthickspace: "a\\negthickspace b",
    enspace: "a\\enspace b",
    nobreakspace: "A\\nobreakspace B",
    hspace: "a\\hspace{1em}b",
    vspace: "a\\vspace{1em}b",
    tiny: "\\tiny",
    scriptsize: "\\scriptsize",
    footnotesize: "\\footnotesize",
    small: "\\small",
    normalsize: "\\normalsize",
    large: "\\large",
    Large: "\\Large",
    LARGE: "\\LARGE",
    huge: "\\huge",
    Huge: "\\Huge",
    alpha: "\\alpha",
    beta: "\\beta",
    gamma: "\\gamma",
    delta: "\\delta",
    epsilon: "\\epsilon",
    zeta: "\\zeta",
    eta: "\\eta",
    theta: "\\theta",
    iota: "\\iota",
    kappa: "\\kappa",
    lambda: "\\lambda",
    mu: "\\mu",
    nu: "\\nu",
    xi: "\\xi",
    omicron: "\\omicron",
    pi: "\\pi",
    rho: "\\rho",
    sigma: "\\sigma",
    tau: "\\tau",
    upsilon: "\\upsilon",
    phi: "\\phi",
    chi: "\\chi",
    psi: "\\psi",
    omega: "\\omega",
    Alpha: "\\Alpha",
    Beta: "\\Beta",
    Gamma: "\\Gamma",
    Delta: "\\Delta",
    Epsilon: "\\Epsilon",
    Zeta: "\\Zeta",
    Eta: "\\Eta",
    Theta: "\\Theta",
    Iota: "\\Iota",
    Kappa: "\\Kappa",
    Lambda: "\\Lambda",
    Mu: "\\Mu",
    Nu: "\\Nu",
    Xi: "\\Xi",
    Omicron: "\\Omicron",
    Pi: "\\Pi",
    Rho: "\\Rho",
    Sigma: "\\Sigma",
    Tau: "\\Tau",
    Upsilon: "\\Upsilon",
    Phi: "\\Phi",
    Chi: "\\Chi",
    Psi: "\\Psi",
    Omega: "\\Omega",
    varepsilon: "\\varepsilon",
    vartheta: "\\vartheta",
    varkappa: "\\varkappa",
    varpi: "\\varpi",
    varrho: "\\varrho",
    varsigma: "\\varsigma",
    varphi: "\\varphi",
    varbeta: "\\varbeta",
    digamma: "\\digamma",
    Digamma: "\\Digamma",
    varGamma: "\\varGamma",
    varDelta: "\\varDelta",
    varTheta: "\\varTheta",
    varLambda: "\\varLambda",
    varXi: "\\varXi",
    varPi: "\\varPi",
    varSigma: "\\varSigma",
    varUpsilon: "\\varUpsilon",
    varPhi: "\\varPhi",
    varPsi: "\\varPsi",
    varOmega: "\\varOmega",
    pm: "x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}",
    mp: "\\cos(x \\pm y) = \\cos x \\cos y \\mp \\sin x \\sin y",
    times: "\\vec{u} \\times \\vec{v}",
    div: "\\div",
    cdot: "\\vec{u} \\cdot \\vec{v}",
    ast: "\\ast",
    star: "\\star",
    circ: "\\circ",
    bullet: "\\bullet",
    diamond: "\\diamond",
    centerdot: "\\centerdot",
    intercal: "\\intercal",
    oplus: "\\oplus",
    ominus: "\\ominus",
    otimes: "\\otimes",
    oslash: "\\oslash",
    odot: "\\odot",
    circledast: "\\circledast",
    circledcirc: "\\circledcirc",
    circleddash: "\\circleddash",
    boxplus: "\\boxplus",
    boxminus: "\\boxminus",
    boxtimes: "\\boxtimes",
    boxdot: "\\boxdot",
    box: "\\box",
    wedge: "(P \\wedge Q) \\vee \\neg R",
    vee: "\\vee",
    land: "\\land",
    lor: "\\lor",
    lnot: "\\lnot",
    neg: "\\neg",
    barwedge: "\\barwedge",
    veebar: "\\veebar",
    doublebarwedge: "\\doublebarwedge",
    curlyvee: "\\curlyvee",
    curlywedge: "\\curlywedge",
    cap: "A \\cap (B \\cup C)",
    cup: "A \\cup (B \\cap C)",
    Cap: "\\Cap",
    Cup: "\\Cup",
    sqcap: "\\sqcap",
    sqcup: "\\sqcup",
    uplus: "\\uplus",
    setminus: "A \\setminus B",
    smallsetminus: "A \\smallsetminus B",
    ltimes: "\\ltimes",
    rtimes: "\\rtimes",
    leftthreetimes: "\\leftthreetimes",
    rightthreetimes: "\\rightthreetimes",
    divideontimes: "\\divideontimes",
    dotplus: "\\dotplus",
    dagger: "\\dagger",
    ddagger: "\\ddagger",
    dag: "\\dag",
    ddag: "\\ddag",
    amalg: "\\amalg",
    wr: "\\wr",
    bigtriangleup: "\\bigtriangleup",
    bigtriangledown: "\\bigtriangledown",
    lhd: "\\lhd",
    rhd: "\\rhd",
    unlhd: "\\unlhd",
    unrhd: "\\unrhd",
    sum: ["\\sum_{i=1}^{n} x_i", "\\sum\\limits_{i=1}^{n} x_i", "\\sum\\nolimits_{i=1}^{n} x_i", "\\displaystyle\\sum_{i=1}^{n} x_i"],
    prod: ["\\prod_{i=1}^{n} x_i", "\\prod\\limits_{i=1}^{n} x_i", "\\prod\\nolimits_{i=1}^{n} x_i"],
    coprod: ["\\coprod_{i=1}^{n} x_i", "\\coprod\\limits_{i=1}^{n} x_i", "\\coprod\\nolimits_{i=1}^{n} x_i"],
    int: ["\\int_{i=1}^{n} x_i", "\\int\\limits_{i=1}^{n} x_i", "\\int\\nolimits_{i=1}^{n} x_i"],
    integral: ["\\integral_{i=1}^{n} x_i", "\\integral\\limits_{i=1}^{n} x_i", "\\integral\\nolimits_{i=1}^{n} x_i"],
    iint: ["\\iint_{i=1}^{n} x_i", "\\iint\\limits_{i=1}^{n} x_i", "\\iint\\nolimits_{i=1}^{n} x_i"],
    iiint: ["\\iiint_{i=1}^{n} x_i", "\\iiint\\limits_{i=1}^{n} x_i", "\\iiint\\nolimits_{i=1}^{n} x_i"],
    iiiint: ["\\iiiint_{i=1}^{n} x_i", "\\iiiint\\limits_{i=1}^{n} x_i", "\\iiiint\\nolimits_{i=1}^{n} x_i"],
    oint: ["\\oint_{i=1}^{n} x_i", "\\oint\\limits_{i=1}^{n} x_i", "\\oint\\nolimits_{i=1}^{n} x_i"],
    oiint: ["\\oiint_{i=1}^{n} x_i", "\\oiint\\limits_{i=1}^{n} x_i", "\\oiint\\nolimits_{i=1}^{n} x_i"],
    oiiint: ["\\oiiint_{i=1}^{n} x_i", "\\oiiint\\limits_{i=1}^{n} x_i", "\\oiiint\\nolimits_{i=1}^{n} x_i"],
    intop: ["\\intop_{i=1}^{n} x_i", "\\intop\\limits_{i=1}^{n} x_i", "\\intop\\nolimits_{i=1}^{n} x_i"],
    smallint: ["\\smallint_{i=1}^{n} x_i", "\\smallint\\limits_{i=1}^{n} x_i", "\\smallint\\nolimits_{i=1}^{n} x_i"],
    ointctrclockwise: ["\\ointctrclockwise_{i=1}^{n} x_i", "\\ointctrclockwise\\limits_{i=1}^{n} x_i", "\\ointctrclockwise\\nolimits_{i=1}^{n} x_i"],
    ointccw: ["\\ointccw_{i=1}^{n} x_i", "\\ointccw\\limits_{i=1}^{n} x_i", "\\ointccw\\nolimits_{i=1}^{n} x_i"],
    ointclockwise: ["\\ointclockwise_{i=1}^{n} x_i", "\\ointclockwise\\limits_{i=1}^{n} x_i", "\\ointclockwise\\nolimits_{i=1}^{n} x_i"],
    ointcw: ["\\ointcw_{i=1}^{n} x_i", "\\ointcw\\limits_{i=1}^{n} x_i", "\\ointcw\\nolimits_{i=1}^{n} x_i"],
    bigvee: ["\\bigvee_{i=1}^{n} x_i", "\\bigvee\\limits_{i=1}^{n} x_i", "\\bigvee\\nolimits_{i=1}^{n} x_i"],
    bigwedge: ["\\bigwedge_{i=1}^{n} x_i", "\\bigwedge\\limits_{i=1}^{n} x_i", "\\bigwedge\\nolimits_{i=1}^{n} x_i"],
    bigcup: ["\\bigcup_{i=1}^{n} x_i", "\\bigcup\\limits_{i=1}^{n} x_i", "\\bigcup\\nolimits_{i=1}^{n} x_i"],
    bigcap: ["\\bigcap_{i=1}^{n} x_i", "\\bigcap\\limits_{i=1}^{n} x_i", "\\bigcap\\nolimits_{i=1}^{n} x_i"],
    bigoplus: ["\\bigoplus_{i=1}^{n} x_i", "\\bigoplus\\limits_{i=1}^{n} x_i", "\\bigoplus\\nolimits_{i=1}^{n} x_i"],
    bigotimes: ["\\bigotimes_{i=1}^{n} x_i", "\\bigotimes\\limits_{i=1}^{n} x_i", "\\bigotimes\\nolimits_{i=1}^{n} x_i"],
    bigodot: ["\\bigodot_{i=1}^{n} x_i", "\\bigodot\\limits_{i=1}^{n} x_i", "\\bigodot\\nolimits_{i=1}^{n} x_i"],
    bigsqcup: ["\\bigsqcup_{i=1}^{n} x_i", "\\bigsqcup\\limits_{i=1}^{n} x_i", "\\bigsqcup\\nolimits_{i=1}^{n} x_i"],
    bigsqcap: ["\\bigsqcap_{i=1}^{n} x_i", "\\bigsqcap\\limits_{i=1}^{n} x_i", "\\bigsqcap\\nolimits_{i=1}^{n} x_i"],
    biguplus: ["\\biguplus_{i=1}^{n} x_i", "\\biguplus\\limits_{i=1}^{n} x_i", "\\biguplus\\nolimits_{i=1}^{n} x_i"],
    leq: "a \\leq b \\leq c",
    geq: "x^2 \\geq 0",
    neq: "x \\neq 0",
    ll: "\\ll",
    gg: "\\gg",
    lll: "\\lll",
    ggg: "\\ggg",
    leqq: "\\leqq",
    geqq: "\\geqq",
    leqslant: "\\leqslant",
    geqslant: "\\geqslant",
    lessgtr: "\\lessgtr",
    gtrless: "\\gtrless",
    lesseqgtr: "\\lesseqgtr",
    gtreqless: "\\gtreqless",
    approx: "\\approx",
    approxeq: "\\approxeq",
    sim: "X \\sim \\mathcal{N}(\\mu, \\sigma^2)",
    simeq: "\\simeq",
    equiv: "x \\equiv y \\pmod{m}",
    cong: "\\cong",
    asymp: "\\asymp",
    doteq: "\\doteq",
    doteqdot: "\\doteqdot",
    eqcirc: "\\eqcirc",
    circeq: "\\circeq",
    bumpeq: "\\bumpeq",
    Bumpeq: "\\Bumpeq",
    lesssim: "\\lesssim",
    gtrsim: "\\gtrsim",
    lessapprox: "\\lessapprox",
    gtrapprox: "\\gtrapprox",
    subset: "\\subset",
    supset: "\\supset",
    subseteq: "A \\subseteq B",
    supseteq: "B \\supseteq A",
    subseteqq: "\\subseteqq",
    supseteqq: "\\supseteqq",
    Subset: "\\Subset",
    Supset: "\\Supset",
    sqsubset: "\\sqsubset",
    sqsupset: "\\sqsupset",
    sqsubseteq: "\\sqsubseteq",
    sqsupseteq: "\\sqsupseteq",
    in: "x \\in A",
    notin: "x \\notin A",
    ni: "\\ni",
    prec: "\\prec",
    succ: "\\succ",
    preceq: "\\preceq",
    succeq: "\\succeq",
    precsim: "\\precsim",
    succsim: "\\succsim",
    precapprox: "\\precapprox",
    succapprox: "\\succapprox",
    preccurlyeq: "\\preccurlyeq",
    succcurlyeq: "\\succcurlyeq",
    curlyeqprec: "\\curlyeqprec",
    curlyeqsucc: "\\curlyeqsucc",
    propto: "\\propto",
    varpropto: "\\varpropto",
    perp: "\\perp",
    mid: "\\mid",
    parallel: "\\parallel",
    shortmid: "\\shortmid",
    shortparallel: "\\shortparallel",
    between: "\\between",
    pitchfork: "\\pitchfork",
    backepsilon: "\\backepsilon",
    vdash: "\\vdash",
    dashv: "\\dashv",
    Vdash: "\\Vdash",
    vDash: "\\vDash",
    Vvdash: "\\Vvdash",
    models: "\\models",
    smile: "\\smile",
    frown: "\\frown",
    bowtie: "\\bowtie",
    Join: "\\Join",
    triangleleft: "\\triangleleft",
    triangleright: "\\triangleright",
    trianglelefteq: "\\trianglelefteq",
    trianglerighteq: "\\trianglerighteq",
    impliedby: "P \\impliedby Q",
    implies: "P \\implies Q",
    iff: "P \\iff Q",
    le: "\\le",
    ge: "\\ge",
    ne: "\\ne",
    owns: "\\owns",
    nleq: "\\nleq",
    ngeq: "\\ngeq",
    nleqq: "\\nleqq",
    ngeqq: "\\ngeqq",
    nleqslant: "\\nleqslant",
    ngeqslant: "\\ngeqslant",
    nless: "\\nless",
    ngtr: "\\ngtr",
    nsubseteq: "\\nsubseteq",
    nsupseteq: "\\nsupseteq",
    nsubseteqq: "\\nsubseteqq",
    nsupseteqq: "\\nsupseteqq",
    subsetneq: "\\subsetneq",
    supsetneq: "\\supsetneq",
    subsetneqq: "\\subsetneqq",
    supsetneqq: "\\supsetneqq",
    nprec: "\\nprec",
    nsucc: "\\nsucc",
    npreceq: "\\npreceq",
    nsucceq: "\\nsucceq",
    precneqq: "\\precneqq",
    succneqq: "\\succneqq",
    precnsim: "\\precnsim",
    succnsim: "\\succnsim",
    ncong: "\\ncong",
    nsim: "\\nsim",
    nmid: "\\nmid",
    nparallel: "\\nparallel",
    nshortmid: "\\nshortmid",
    nshortparallel: "\\nshortparallel",
    nvdash: "\\nvdash",
    nvDash: "\\nvDash",
    nVdash: "\\nVdash",
    nVDash: "\\nVDash",
    ntriangleleft: "\\ntriangleleft",
    ntriangleright: "\\ntriangleright",
    ntrianglelefteq: "\\ntrianglelefteq",
    ntrianglerighteq: "\\ntrianglerighteq",
    coloneq: "\\coloneq",
    Coloneq: "\\Coloneq",
    coloneqq: "\\coloneqq",
    Coloneqq: "\\Coloneqq",
    eqcolon: "\\eqcolon",
    Eqcolon: "\\Eqcolon",
    colonapprox: "\\colonapprox",
    Colonapprox: "\\Colonapprox",
    colonsim: "\\colonsim",
    Colonsim: "\\Colonsim",
    ratio: "\\ratio",
    coloncolon: "\\coloncolon",
    coloncoloneq: "\\coloncoloneq",
    coloncoloneqq: "\\coloncoloneqq",
    equalscolon: "\\equalscolon",
    equalscoloncolon: "\\equalscoloncolon",
    rightarrow: "f: A \\rightarrow B",
    leftarrow: "x \\leftarrow y + 1",
    Rightarrow: "A \\Rightarrow B",
    Leftarrow: "A \\Leftarrow B",
    leftrightarrow: "A \\leftrightarrow B",
    Leftrightarrow: "A \\Leftrightarrow B",
    uparrow: "A \\uparrow B",
    downarrow: "A \\downarrow B",
    Uparrow: "A \\Uparrow B",
    Downarrow: "A \\Downarrow B",
    updownarrow: "A \\updownarrow B",
    Updownarrow: "A \\Updownarrow B",
    to: "f: A \\to B",
    gets: "x \\gets y + 1",
    mapsto: "x \\mapsto x^2",
    nearrow: "A \\nearrow B",
    searrow: "A \\searrow B",
    nwarrow: "A \\nwarrow B",
    swarrow: "A \\swarrow B",
    rightharpoonup: "A \\rightharpoonup B",
    rightharpoondown: "A \\rightharpoondown B",
    leftharpoonup: "A \\leftharpoonup B",
    leftharpoondown: "A \\leftharpoondown B",
    upharpoonright: "A \\upharpoonright B",
    upharpoonleft: "A \\upharpoonleft B",
    downharpoonright: "A \\downharpoonright B",
    downharpoonleft: "A \\downharpoonleft B",
    rightleftharpoons: "A \\rightleftharpoons B",
    leftrightharpoons: "A \\leftrightharpoons B",
    hookrightarrow: "A \\hookrightarrow B",
    hookleftarrow: "A \\hookleftarrow B",
    longrightarrow: "x_n \\longrightarrow x",
    longleftarrow: "A \\longleftarrow B",
    longleftrightarrow: "A \\longleftrightarrow B",
    Longrightarrow: "A \\Longrightarrow B",
    Longleftarrow: "A \\Longleftarrow B",
    Longleftrightarrow: "P \\Longleftrightarrow Q",
    longmapsto: "A \\longmapsto B",
    twoheadrightarrow: "A \\twoheadrightarrow B",
    twoheadleftarrow: "A \\twoheadleftarrow B",
    rightarrowtail: "A \\rightarrowtail B",
    leftarrowtail: "A \\leftarrowtail B",
    looparrowright: "A \\looparrowright B",
    looparrowleft: "A \\looparrowleft B",
    curvearrowright: "A \\curvearrowright B",
    curvearrowleft: "A \\curvearrowleft B",
    circlearrowright: "A \\circlearrowright B",
    circlearrowleft: "A \\circlearrowleft B",
    dashrightarrow: "A \\dashrightarrow B",
    dashleftarrow: "A \\dashleftarrow B",
    rightsquigarrow: "A \\rightsquigarrow B",
    leftrightsquigarrow: "A \\leftrightsquigarrow B",
    leadsto: "A \\leadsto B",
    multimap: "A \\multimap B",
    nrightarrow: "A \\nrightarrow B",
    nleftarrow: "A \\nleftarrow B",
    nRightarrow: "A \\nRightarrow B",
    nLeftarrow: "A \\nLeftarrow B",
    nleftrightarrow: "A \\nleftrightarrow B",
    nLeftrightarrow: "A \\nLeftrightarrow B",
    sin: "\\sin^2 x + \\cos^2 x = 1",
    cos: "\\cos(x + y)",
    tan: "\\tan(x + y)",
    cot: "\\cot",
    sec: "\\sec",
    csc: "\\csc",
    arcsin: "\\arcsin",
    arccos: "\\arccos",
    arctan: "\\arctan",
    arccot: "\\arccot",
    arcsec: "\\arcsec",
    arccsc: "\\arccsc",
    sinh: "\\sinh",
    cosh: "\\cosh",
    tanh: "\\tanh",
    coth: "\\coth",
    sech: "\\sech",
    csch: "\\csch",
    log: "\\log_b a = \\frac{\\ln a}{\\ln b}",
    ln: "\\ln(xy) = \\ln x + \\ln y",
    lg: "\\lg",
    exp: "\\exp(i\\theta) = \\cos\\theta + i\\sin\\theta",
    lim: "\\lim_{x \\to 0} \\frac{\\sin x}{x} = 1",
    limsup: "\\limsup_{n \\to \\infty} a_n",
    liminf: "\\liminf_{n \\to \\infty} a_n",
    varlimsup: "\\varlimsup",
    varliminf: "\\varliminf",
    max: "\\max_{x \\in [0,1]} f(x)",
    min: "\\min_{x \\in [0,1]} f(x)",
    sup: "\\sup_{x \\in A} f(x)",
    inf: "\\inf_{x \\in A} f(x)",
    argmax: "\\argmax_{\\theta \\in \\Theta} L(\\theta)",
    argmin: "\\argmin_w \\sum_{i=1}^n (y_i - wx_i)^2",
    det: "\\det(A - \\lambda I) = 0",
    deg: "\\deg",
    gcd: "\\gcd(a, b)",
    lcm: "\\lcm",
    ker: "\\ker",
    hom: "\\hom",
    dim: "\\dim",
    arg: "\\arg",
    Pr: "\\Pr",
    tr: "\\tr",
    rank: "\\rank",
    span: "\\span",
    sgn: "\\sgn",
    diag: "\\diag",
    injlim: "\\injlim",
    projlim: "\\projlim",
    varinjlim: "\\varinjlim",
    varprojlim: "\\varprojlim",
    bmod: "\\bmod",
    pmod: "\\pmod{x}",
    mod: "\\mod{x}",
    pod: "\\pod{x}",
    left: "\\left( \\frac{a}{b} \\right)",
    right: "\\left( \\frac{a}{b} \\right)",
    middle: "\\left\\{ x \\middle| x > 0 \\right\\}",
    langle: "\\left\\langle x, y \\right\\rangle",
    rangle: "\\left\\langle x, y \\right\\rangle",
    lfloor: "\\left\\lfloor \\frac{n}{2} \\right\\rfloor",
    rfloor: "\\left\\lfloor \\frac{n}{2} \\right\\rfloor",
    lceil: "\\left\\lceil \\frac{n}{2} \\right\\rceil",
    rceil: "\\left\\lceil \\frac{n}{2} \\right\\rceil",
    vert: "\\left\\vert x \\right\\vert",
    Vert: "\\left\\Vert \\vec{x} \\right\\Vert",
    lvert: "\\left\\lvert x \\right\\rvert",
    rvert: "\\left\\lvert x \\right\\rvert",
    lVert: "\\left\\lVert \\vec{x} \\right\\rVert",
    rVert: "\\left\\lVert \\vec{x} \\right\\rVert",
    ulcorner: "\\ulcorner",
    urcorner: "\\urcorner",
    llcorner: "\\llcorner",
    lrcorner: "\\lrcorner",
    infty: "\\infty",
    partial: "\\frac{\\partial f}{\\partial x}",
    nabla: "\\nabla \\cdot \\vec{F}",
    forall: "\\forall x \\in \\mathbb{R}",
    exists: "\\exists x \\in A",
    nexists: "\\nexists x \\in A",
    not: "\\not",
    top: "\\top",
    bot: "\\bot",
    emptyset: "\\emptyset \\subseteq A",
    varnothing: "\\varnothing",
    ldots: "\\ldots",
    cdots: "x_1 + x_2 + \\cdots + x_n",
    vdots: "\\begin{matrix} a \\\\ \\vdots \\\\ z \\end{matrix}",
    ddots: "\\begin{matrix} 1 & 0 & 0 \\\\ 0 & \\ddots & 0 \\\\ 0 & 0 & 1 \\end{matrix}",
    hdots: "\\hdots",
    iddots: "\\iddots",
    dots: "x_1, x_2, \\dots, x_n",
    dotsb: "\\dotsb",
    dotsc: "\\dotsc",
    dotsi: "\\dotsi",
    dotsm: "\\dotsm",
    dotso: "\\dotso",
    aleph: "\\aleph",
    beth: "\\beth",
    gimel: "\\gimel",
    daleth: "\\daleth",
    hbar: "\\hbar",
    hslash: "\\hslash",
    ell: "\\ell",
    imath: "\\imath",
    jmath: "\\jmath",
    Re: "\\Re",
    Im: "\\Im",
    wp: "\\wp",
    complement: "\\complement",
    Finv: "\\Finv",
    Game: "\\Game",
    mho: "\\mho",
    eth: "\\eth",
    prime: "f\\prime(x)",
    backprime: "\\backprime",
    backslash: "\\backslash",
    diagup: "\\diagup",
    diagdown: "\\diagdown",
    therefore: "\\therefore P \\Rightarrow Q",
    because: "\\because P",
    angle: "\\angle",
    measuredangle: "\\measuredangle",
    sphericalangle: "\\sphericalangle",
    triangle: "\\triangle",
    blacktriangle: "\\blacktriangle",
    blacktriangledown: "\\blacktriangledown",
    blacktriangleleft: "\\blacktriangleleft",
    blacktriangleright: "\\blacktriangleright",
    degree: "\\degree",
    square: "\\square",
    blacksquare: "\\blacksquare",
    lozenge: "\\lozenge",
    blacklozenge: "\\blacklozenge",
    bigstar: "\\bigstar",
    circledR: "\\circledR",
    circledS: "\\circledS",
    flat: "\\flat",
    natural: "\\natural",
    sharp: "\\sharp",
    clubsuit: "\\clubsuit",
    diamondsuit: "\\diamondsuit",
    heartsuit: "\\heartsuit",
    spadesuit: "\\spadesuit",
    S: "\\S",
    P: "\\P",
    copyright: "\\copyright",
    pounds: "\\pounds",
    yen: "\\yen",
    checkmark: "\\checkmark",
    maltese: "\\maltese",
    llbracket: ["\\llbracket", "\\left\\llbracket x \\right\\rrbracket"],
    rrbracket: ["\\rrbracket", "\\left\\llbracket x \\right\\rrbracket"],
    lgroup: ["\\lgroup", "\\left\\lgroup x \\right\\rgroup"],
    rgroup: ["\\rgroup", "\\left\\lgroup x \\right\\rgroup"],
    lmoustache: ["\\lmoustache", "\\left\\lmoustache x \\right\\rmoustache"],
    rmoustache: ["\\rmoustache", "\\left\\lmoustache x \\right\\rmoustache"],
    bracevert: "\\bracevert",
    lBrace: ["\\lBrace", "\\left\\lBrace x \\right\\rBrace"],
    rBrace: ["\\rBrace", "\\left\\lBrace x \\right\\rBrace"],
    cdotp: "\\cdotp",
    ldotp: "\\ldotp",
    colon: "\\colon",
    AA: "\\AA",
    ss: "\\ss",
    ae: "\\ae",
    oe: "\\oe",
    AE: "\\AE",
    OE: "\\OE",
    o: "\\o",
    O: "\\O",
    i: "\\i",
    j: "\\j",
    displaystyle: ["\\displaystyle\\frac{1}{1 + x}", "\\displaystyle\\sum_{i=1}^{n} x_i", "\\displaystyle\\binom{n}{k}"],
    textstyle: ["\\textstyle\\frac{1}{1 + x}", "\\textstyle\\sum_{i=1}^{n} x_i", "\\textstyle\\binom{n}{k}"],
    scriptstyle: "\\scriptstyle",
    scriptscriptstyle: "\\scriptscriptstyle",
    phantom: "\\phantom{x}",
    hphantom: "\\hphantom{x}",
    vphantom: "\\vphantom{x}",
    smash: "\\smash{x}",
    color: "\\color{x}",
    textcolor: "\\textcolor{red}{x + y}",
    colorbox: "\\colorbox{yellow}{x + y}",
    fcolorbox: "\\fcolorbox{red}{yellow}{x + y}",
    boxed: "\\boxed{x^2 + y^2 = r^2}",
    cancel: "\\cancel{x}",
    bcancel: "\\bcancel{x}",
    xcancel: "\\xcancel{x}",
    sout: "\\sout{x}",
    operatorname: "\\operatorname{rank}(A)",
    "operatorname*": "\\operatorname*{argmax}_{x \\in A} f(x)",
    tag: "E = mc^2 \\tag{1}",
    "tag*": "E = mc^2 \\tag*{Einstein}",
    substack: "\\sum_{\\substack{i=1 \\\\ i \\ne j}}^n a_i",
    limits: "\\sum\\limits_{i=1}^{n} x_i",
    nolimits: "\\sum\\nolimits_{i=1}^{n} x_i",
    rule: "\\rule{2em}{0.4pt}",
    href: "\\href{https://example.com}{x}",
    url: "\\url{https://example.com}",
    kern: "a\\kern{1em}b",
    mkern: "a\\mkern{3mu}b",
    mskip: "a\\mskip{3mu}b",
    laplace: "\\laplace f(t)",
    Fourier: "\\Fourier f",
    fourier: "\\fourier f",
    Mellin: "\\Mellin f",
    mellin: "\\mellin f",
    "!": "a\\!b",
    ",": "a\\,b",
    ":": "a\\:b",
    ";": "a\\;b",
    " ": "a\\ b",
    matrix: ["\\begin{matrix} a & b \\\\ c & d \\end{matrix}", "\\matrix{a & b \\\\ c & d}"],
    pmatrix: ["\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}", "\\pmatrix{a & b \\\\ c & d}"],
    bmatrix: ["\\begin{bmatrix} 1 & 0 \\\\ 0 & 1 \\end{bmatrix}", "\\bmatrix{1 & 0 \\\\ 0 & 1}"],
    Bmatrix: ["\\begin{Bmatrix} a & b \\\\ c & d \\end{Bmatrix}", "\\Bmatrix{a & b \\\\ c & d}"],
    vmatrix: ["\\begin{vmatrix} a & b \\\\ c & d \\end{vmatrix}", "\\vmatrix{a & b \\\\ c & d}"],
    Vmatrix: ["\\begin{Vmatrix} a & b \\\\ c & d \\end{Vmatrix}", "\\Vmatrix{a & b \\\\ c & d}"],
    cases: ["f(x) = \\begin{cases} x^2 & x \\geq 0 \\\\ -x & x < 0 \\end{cases}", "\\cases{x^2 & x \\geq 0 \\\\ -x & x < 0}"],
    rcases: ["\\begin{rcases} a & b \\\\ c & d \\end{rcases}", "\\rcases{a & b \\\\ c & d}"],
    dcases: ["\\begin{dcases} a & b \\\\ c & d \\end{dcases}", "\\dcases{a & b \\\\ c & d}"],
    align: ["\\begin{align} a &= b + c \\\\ d &= e - f \\end{align}", "\\align{a &= b + c \\\\ d &= e - f}"],
    aligned: ["\\begin{aligned} a &= b + c \\\\ d &= e - f \\end{aligned}", "\\aligned{a &= b + c \\\\ d &= e - f}"],
    gather: ["\\begin{gather} x + y = 1 \\\\ x - y = 0 \\end{gather}", "\\gather{x + y = 1 \\\\ x - y = 0}"],
    gathered: ["\\begin{gathered} x + y = 1 \\\\ x - y = 0 \\end{gathered}", "\\gathered{x + y = 1 \\\\ x - y = 0}"],
    split: ["\\begin{split} a &= b + c \\\\ &= d + e \\end{split}", "\\split{a &= b + c \\\\ &= d + e}"],
    multline: ["\\begin{multline} a + b + c \\\\ d + e + f \\end{multline}", "\\multline{a + b + c \\\\ d + e + f}"],
    equation: ["\\begin{equation} E = mc^2 \\end{equation}", "\\equation{E = mc^2}"],
    array: ["\\begin{array} a & b \\\\ c & d \\end{array}", "\\array{a & b \\\\ c & d}"],
    smallmatrix: ["\\begin{smallmatrix} a & b \\\\ c & d \\end{smallmatrix}", "\\smallmatrix{a & b \\\\ c & d}"],
    subarray: ["\\begin{subarray} i=1 \\\\ i\\ne j \\end{subarray}", "\\subarray{i=1 \\\\ i\\ne j}"],
    "\\": "\\\\",
};
