// Explicit Command Name -> LaTeX Code mapping data structure (supports single string or array of test cases)
export const COMMAND_LATEX_MAP: Record<string, string | string[]> = {
    frac: ["\\frac{a}{b}", "\\frac{x + y}{x - y}", "\\frac{1}{1 + \\frac{1}{x}}", "\\frac{\\partial^2 f}{\\partial x \\partial y}"],
    dfrac: ["\\dfrac{a}{b}", "\\dfrac{\\lim_{x \\to 0} (f(x) - f(0))}{x}", "\\dfrac{d}{dx} \\left( \\dfrac{x}{1+x^2} \\right)"],
    tfrac: ["\\tfrac{a}{b}", "\\tfrac{1}{2}a + \\tfrac{3}{4}b"],
    cfrac: ["\\cfrac{a}{b}", "a_0 + \\cfrac{1}{a_1 + \\cfrac{1}{a_2 + \\cfrac{1}{a_3}}}"],
    sfrac: ["\\sfrac{a}{b}", "\\sfrac{x + y}{z + w}"],
    nicefrac: ["\\nicefrac{a}{b}", "\\nicefrac{x + y}{z + w}"],
    flatfrac: ["\\flatfrac{a}{b}", "\\flatfrac{x + y}{z + w}"],
    sqrt: ["\\sqrt{x}", "\\sqrt{a^2 + b^2}", "\\sqrt[n]{x_1^n + x_2^n + \\dots + x_k^n}"],
    binom: ["\\binom{a}{b}", "\\binom{n}{k}", "\\binom{n}{0} + \\binom{n}{1} + \\dots + \\binom{n}{n} = 2^n"],
    dbinom: ["\\dbinom{a}{b}", "\\dbinom{x + y}{z + w}"],
    tbinom: ["\\tbinom{a}{b}", "\\tbinom{x + y}{z + w}"],
    choose: ["{a \\choose b}", "{n \\choose k} = \\frac{n!}{k!(n-k)!}"],
    genfrac: ["\\genfrac", "\\genfrac"],
    above: ["{a \\above b}", "{n \\above k}"],
    atop: ["{a \\atop b}", "{n \\atop k}"],
    over: ["{a \\over b}", "{n \\over k}"],
    hat: ["\\hat{a}", "\\hat{x}", "\\hat{\\theta} + \\hat{\\phi}"],
    check: ["\\check{a}", "\\check{x}"],
    breve: ["\\breve{a}", "\\breve{x}"],
    acute: ["\\acute{a}", "\\acute{x}"],
    grave: ["\\grave{a}", "\\grave{x}"],
    tilde: ["\\tilde{a}", "\\tilde{x}_i"],
    bar: ["\\bar{a}", "\\bar{x} + \\bar{y}", "\\bar{z} = x - iy"],
    vec: ["\\vec{a}", "\\vec{v} = (v_x, v_y, v_z)", "\\vec{F} = m \\vec{a}"],
    dot: ["\\dot{a}", "\\dot{x}(t)", "\\dot{x} = v"],
    ddot: ["\\ddot{a}", "\\ddot{x}(t)", "\\ddot{x} + \\omega_0^2 x = 0"],
    dddot: ["\\dddot{a}", "\\dddot{x}(t)"],
    ddddot: ["\\ddddot{a}", "\\ddddot{x}", "\\ddddot{A + B}"],
    mathring: ["\\mathring{a}", "\\mathring{A}"],
    widehat: ["\\widehat{ab}", "\\widehat{x + y + z}"],
    widetilde: ["\\widetilde{ab}", "\\widetilde{A \\cup B}"],
    widecheck: ["\\widecheck{a}", "\\widecheck{x}", "\\widecheck{A + B}"],
    wideparen: ["\\wideparen{a}", "\\wideparen{x}", "\\wideparen{A + B}"],
    overline: ["\\overline{ab}", "\\overline{A \\cup B} = \\overline{A} \\cap \\overline{B}"],
    underline: ["\\underline{ab}", "\\underline{x_1 + x_2 + \\dots + x_n}"],
    overbrace: ["\\overbrace{ab}", "\\overbrace{a + b + c + d}^{4\\text{ terms}}", "\\overbrace{x_1 + x_2 + \\dots + x_n}^{n \\text{ variables}}"],
    underbrace: ["\\underbrace{ab}", "\\underbrace{1 + 2 + \\dots + n}_{\\frac{n(n+1)}{2}}"],
    overgroup: ["\\overgroup{a}", "\\overgroup{x}", "\\overgroup{A + B}"],
    undergroup: ["\\undergroup{a}", "\\undergroup{x}", "\\undergroup{A + B}"],
    overparen: ["\\overparen{a}", "\\overparen{x}", "\\overparen{A + B}"],
    underparen: ["\\underparen{a}", "\\underparen{x}", "\\underparen{A + B}"],
    overleftarrow: ["\\overleftarrow{ab}", "\\overleftarrow{AB}"],
    overrightarrow: ["\\overrightarrow{ab}", "\\overrightarrow{AB} + \\overrightarrow{BC} = \\overrightarrow{AC}"],
    overleftrightarrow: ["\\overleftrightarrow{a}", "\\overleftrightarrow{x_1 + x_2}"],
    underleftarrow: ["\\underleftarrow{a}", "\\underleftarrow{x_1 + x_2}"],
    underrightarrow: ["\\underrightarrow{a}", "\\underrightarrow{x_1 + x_2}"],
    underleftrightarrow: ["\\underleftrightarrow{a}", "\\underleftrightarrow{x_1 + x_2}"],
    utilde: ["\\utilde{a}", "\\utilde{x}", "\\utilde{A + B}"],
    overset: ["\\overset{a}{b}", "x \\overset{\\text{def}}{=} y", "A \\overset{f}{\\longrightarrow} B \\overset{g}{\\longrightarrow} C"],
    underset: ["\\underset{a}{b}", "\\underset{x \\to 0}{\\lim} \\frac{\\sin x}{x} = 1"],
    stackrel: ["a \\stackrel{x}{b}", "X_n \\stackrel{d}{\\longrightarrow} X"],
    xrightarrow: ["a \\xrightarrow{} b", "A \\xrightarrow{f} B", "x_n \\xrightarrow[n \\to \\infty]{\\text{strongly}} x"],
    xleftarrow: ["a \\xleftarrow{} b", "A \\xleftarrow[bottom]{top} B"],
    xLeftarrow: ["a \\xLeftarrow{} b", "A \\xLeftarrow{\\text{proof}} B"],
    xRightarrow: ["a \\xRightarrow{} b", "A \\xRightarrow{\\text{implies}} B"],
    xLeftrightarrow: ["a \\xLeftrightarrow{} b", "A \\xLeftrightarrow{\\text{iff}} B"],
    xleftrightarrow: ["a \\xleftrightarrow[b]{c} d", "x \\xleftrightarrow[n \\to \\infty]{\\text{def}} y"],
    xhookleftarrow: ["a \\xhookleftarrow[b]{c} d", "x \\xhookleftarrow[n \\to \\infty]{\\text{def}} y"],
    xhookrightarrow: ["a \\xhookrightarrow[b]{c} d", "x \\xhookrightarrow[n \\to \\infty]{\\text{def}} y"],
    xmapsto: ["a \\xmapsto{} b", "x \\xmapsto[f]{\\text{map}} f(x)"],
    xtwoheadleftarrow: ["a \\xtwoheadleftarrow[b]{c} d", "x \\xtwoheadleftarrow[n \\to \\infty]{\\text{def}} y"],
    xtwoheadrightarrow: ["a \\xtwoheadrightarrow[b]{c} d", "x \\xtwoheadrightarrow[n \\to \\infty]{\\text{def}} y"],
    xlongequal: ["a \\xlongequal[b]{c} d", "x \\xlongequal[n \\to \\infty]{\\text{def}} y"],
    xrightharpoonup: ["a \\xrightharpoonup[b]{c} d", "x \\xrightharpoonup[n \\to \\infty]{\\text{def}} y"],
    xrightharpoondown: ["a \\xrightharpoondown[b]{c} d", "x \\xrightharpoondown[n \\to \\infty]{\\text{def}} y"],
    xleftharpoonup: ["a \\xleftharpoonup[b]{c} d", "x \\xleftharpoonup[n \\to \\infty]{\\text{def}} y"],
    xleftharpoondown: ["a \\xleftharpoondown[b]{c} d", "x \\xleftharpoondown[n \\to \\infty]{\\text{def}} y"],
    xrightleftharpoons: ["a \\xrightleftharpoons[b]{c} d", "x \\xrightleftharpoons[n \\to \\infty]{\\text{def}} y"],
    xleftrightharpoons: ["a \\xleftrightharpoons[b]{c} d", "x \\xleftrightharpoons[n \\to \\infty]{\\text{def}} y"],
    mathrm: ["\\mathrm{a}", "\\mathrm{d}x", "\\mathrm{e}^{i \\pi} + 1 = 0"],
    mathbf: ["\\mathbf{a}", "\\mathbf{x}", "\\mathbf{A} \\mathbf{x} = \\mathbf{b}"],
    mathit: ["\\mathit{ab}"],
    mathbb: ["\\mathbb{R}", "\\mathbb{N}", "\\mathbb{C}", "\\mathbb{R}^n \\to \\mathbb{R}^m"],
    mathcal: ["\\mathcal{A}", "\\mathcal{L}\\{f(t)\\}", "\\mathcal{O}(n \\log n)"],
    mathfrak: ["\\mathfrak{a}", "\\mathfrak{g}", "\\mathfrak{sl}_2(\\mathbb{C})"],
    mathsf: ["\\mathsf{ab}"],
    mathtt: ["\\mathtt{ab}"],
    mathnormal: ["\\mathnormal{a}", "\\mathnormal{AB}", "\\mathnormal{x_1 + x_2}"],
    mathscr: ["\\mathscr{H}", "\\mathscr{F}\\{f\\}"],
    mathbfit: ["\\mathbfit{a}", "\\mathbfit{AB}", "\\mathbfit{x_1 + x_2}"],
    mathsfit: ["\\mathsfit{a}", "\\mathsfit{AB}", "\\mathsfit{x_1 + x_2}"],
    mathbfsfit: ["\\mathbfsfit{a}", "\\mathbfsfit{AB}", "\\mathbfsfit{x_1 + x_2}"],
    boldsymbol: ["\\boldsymbol{a}", "\\boldsymbol{AB}", "\\boldsymbol{x_1 + x_2}"],
    bm: ["\\bm{a}", "\\bm{AB}", "\\bm{x_1 + x_2}"],
    pmb: ["\\pmb{a}", "\\pmb{AB}", "\\pmb{x_1 + x_2}"],
    text: ["\\text{a}", "\\text{AB}", "\\text{x_1 + x_2}"],
    mbox: ["\\mbox{a}", "\\mbox{AB}", "\\mbox{x_1 + x_2}"],
    textbf: ["\\textbf{a}", "\\textbf{AB}", "\\textbf{x_1 + x_2}"],
    textit: ["\\textit{a}", "\\textit{AB}", "\\textit{x_1 + x_2}"],
    textrm: ["\\textrm{a}", "\\textrm{AB}", "\\textrm{x_1 + x_2}"],
    textsf: ["\\textsf{a}", "\\textsf{AB}", "\\textsf{x_1 + x_2}"],
    texttt: ["\\texttt{a}", "\\texttt{AB}", "\\texttt{x_1 + x_2}"],
    textnormal: ["\\textnormal{a}", "\\textnormal{AB}", "\\textnormal{x_1 + x_2}"],
    textup: ["\\textup{a}", "\\textup{AB}", "\\textup{x_1 + x_2}"],
    scr: ["\\scr{a}", "\\scr{AB}", "\\scr{x_1 + x_2}"],
    cal: ["\\cal{a}", "\\cal{AB}", "\\cal{x_1 + x_2}"],
    Bbb: ["\\Bbb{a}", "\\Bbb{AB}", "\\Bbb{x_1 + x_2}"],
    frak: ["\\frak{a}", "\\frak{AB}", "\\frak{x_1 + x_2}"],
    rm: ["\\rm{a}", "\\rm{AB}", "\\rm{x_1 + x_2}"],
    bf: ["\\bf{a}", "\\bf{AB}", "\\bf{x_1 + x_2}"],
    it: ["\\it{a}", "\\it{AB}", "\\it{x_1 + x_2}"],
    sf: ["\\sf{a}", "\\sf{AB}", "\\sf{x_1 + x_2}"],
    tt: ["\\tt{a}", "\\tt{AB}", "\\tt{x_1 + x_2}"],
    quad: ["\\quad", "\\quad"],
    qquad: ["\\qquad", "\\qquad"],
    thinspace: ["\\thinspace", "\\thinspace"],
    medspace: ["\\medspace", "\\medspace"],
    thickspace: ["\\thickspace", "\\thickspace"],
    negthinspace: ["a \\negthinspace b", "x \\negthinspace y", "A \\negthinspace B"],
    negmedspace: ["a \\negmedspace b", "x \\negmedspace y", "A \\negmedspace B"],
    negthickspace: ["a \\negthickspace b", "x \\negthickspace y", "A \\negthickspace B"],
    enspace: ["\\enspace", "\\enspace"],
    nobreakspace: ["a \\nobreakspace b", "x \\nobreakspace y", "A \\nobreakspace B"],
    hspace: ["\\hspace{a}", "\\hspace{x_1 + x_2}"],
    vspace: ["\\vspace{a}", "\\vspace{x_1 + x_2}"],
    tiny: ["\\tiny", "\\tiny"],
    scriptsize: ["\\scriptsize", "\\scriptsize"],
    footnotesize: ["\\footnotesize", "\\footnotesize"],
    small: ["\\small", "\\small"],
    normalsize: ["a \\normalsize b", "x \\normalsize y", "A \\normalsize B"],
    large: ["\\large", "\\large"],
    Large: ["\\Large", "\\Large"],
    LARGE: ["\\LARGE", "\\LARGE"],
    huge: ["\\huge", "\\huge"],
    Huge: ["\\Huge", "\\Huge"],
    alpha: ["\\alpha", "\\alpha"],
    beta: ["\\beta", "\\beta"],
    gamma: ["\\gamma", "\\gamma"],
    delta: ["\\delta", "\\delta"],
    epsilon: ["\\epsilon", "\\epsilon"],
    zeta: ["\\zeta", "\\zeta"],
    eta: ["\\eta", "\\eta"],
    theta: ["\\theta", "\\theta"],
    iota: ["\\iota", "\\iota"],
    kappa: ["\\kappa", "\\kappa"],
    lambda: ["\\lambda", "\\lambda"],
    mu: ["\\mu", "\\mu"],
    nu: ["a \\nu b", "x \\nu y", "A \\nu B"],
    xi: ["a \\xi b", "x \\xi y", "f(x) \\xi g(y)"],
    omicron: ["\\omicron", "\\omicron"],
    pi: ["\\pi", "\\pi"],
    rho: ["\\rho", "\\rho"],
    sigma: ["\\sigma", "\\sigma"],
    tau: ["\\tau", "\\tau"],
    upsilon: ["\\upsilon", "\\upsilon"],
    phi: ["\\phi", "\\phi"],
    chi: ["\\chi", "\\chi"],
    psi: ["\\psi", "\\psi"],
    omega: ["\\omega", "\\omega"],
    Alpha: ["\\Alpha", "\\Alpha"],
    Beta: ["\\Beta", "\\Beta"],
    Gamma: ["\\Gamma", "\\Gamma"],
    Delta: ["\\Delta", "\\Delta"],
    Epsilon: ["\\Epsilon", "\\Epsilon"],
    Zeta: ["\\Zeta", "\\Zeta"],
    Eta: ["\\Eta", "\\Eta"],
    Theta: ["\\Theta", "\\Theta"],
    Iota: ["\\Iota", "\\Iota"],
    Kappa: ["\\Kappa", "\\Kappa"],
    Lambda: ["\\Lambda", "\\Lambda"],
    Mu: ["\\Mu", "\\Mu"],
    Nu: ["\\Nu", "\\Nu"],
    Xi: ["\\Xi", "\\Xi"],
    Omicron: ["\\Omicron", "\\Omicron"],
    Pi: ["\\Pi", "\\Pi"],
    Rho: ["\\Rho", "\\Rho"],
    Sigma: ["\\Sigma", "\\Sigma"],
    Tau: ["\\Tau", "\\Tau"],
    Upsilon: ["\\Upsilon", "\\Upsilon"],
    Phi: ["\\Phi", "\\Phi"],
    Chi: ["\\Chi", "\\Chi"],
    Psi: ["\\Psi", "\\Psi"],
    Omega: ["\\Omega", "\\Omega"],
    varepsilon: ["\\varepsilon", "\\varepsilon"],
    vartheta: ["\\vartheta", "\\vartheta"],
    varkappa: ["\\varkappa", "\\varkappa"],
    varpi: ["\\varpi", "\\varpi"],
    varrho: ["\\varrho", "\\varrho"],
    varsigma: ["\\varsigma", "\\varsigma"],
    varphi: ["\\varphi", "\\varphi"],
    varbeta: ["\\varbeta", "\\varbeta"],
    digamma: ["\\digamma", "\\digamma"],
    Digamma: ["\\Digamma", "\\Digamma"],
    varGamma: ["\\varGamma", "\\varGamma"],
    varDelta: ["\\varDelta", "\\varDelta"],
    varTheta: ["\\varTheta", "\\varTheta"],
    varLambda: ["\\varLambda", "\\varLambda"],
    varXi: ["\\varXi", "\\varXi"],
    varPi: ["\\varPi", "\\varPi"],
    varSigma: ["\\varSigma", "\\varSigma"],
    varUpsilon: ["\\varUpsilon", "\\varUpsilon"],
    varPhi: ["\\varPhi", "\\varPhi"],
    varPsi: ["\\varPsi", "\\varPsi"],
    varOmega: ["\\varOmega", "\\varOmega"],
    pm: ["a \\pm b", "x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}"],
    mp: ["a \\mp b", "\\cos(x \\pm y) = \\cos x \\cos y \\mp \\sin x \\sin y"],
    times: ["a \\times b", "A \\times B", "\\vec{u} \\times \\vec{v} = \\vec{w}"],
    div: ["a \\div b", "(x + y) \\div (z + w)"],
    cdot: ["a \\cdot b", "\\vec{a} \\cdot \\vec{b} = \\|a\\| \\|b\\| \\cos \\theta"],
    ast: ["a \\ast b", "x \\ast y", "(A + B) \\ast (C + D)"],
    star: ["a \\star b", "x \\star y", "(A + B) \\star (C + D)"],
    circ: ["a \\circ b", "x \\circ y", "(A + B) \\circ (C + D)"],
    bullet: ["a \\bullet b", "x \\bullet y", "(A + B) \\bullet (C + D)"],
    diamond: ["\\diamond", "\\diamond"],
    centerdot: ["\\centerdot", "\\centerdot"],
    intercal: ["\\intercal", "\\intercal"],
    oplus: ["a \\oplus b", "x \\oplus y", "(A + B) \\oplus (C + D)"],
    ominus: ["a \\ominus b", "x \\ominus y", "(A + B) \\ominus (C + D)"],
    otimes: ["a \\otimes b", "x \\otimes y", "(A + B) \\otimes (C + D)"],
    oslash: ["a \\oslash b", "x \\oslash y", "(A + B) \\oslash (C + D)"],
    odot: ["\\odot", "\\odot"],
    circledast: ["a \\circledast b", "x \\circledast y", "(A + B) \\circledast (C + D)"],
    circledcirc: ["a \\circledcirc b", "x \\circledcirc y", "(A + B) \\circledcirc (C + D)"],
    circleddash: ["a \\circleddash b", "x \\circleddash y", "(A + B) \\circleddash (C + D)"],
    boxplus: ["a \\boxplus b", "x \\boxplus y", "(A + B) \\boxplus (C + D)"],
    boxminus: ["a \\boxminus b", "x \\boxminus y", "(A + B) \\boxminus (C + D)"],
    boxtimes: ["a \\boxtimes b", "x \\boxtimes y", "(A + B) \\boxtimes (C + D)"],
    boxdot: ["a \\boxdot b", "x \\boxdot y", "(A + B) \\boxdot (C + D)"],
    box: ["a \\box b", "x \\box y", "(A + B) \\box (C + D)"],
    wedge: ["a \\wedge b", "x \\wedge y", "(A + B) \\wedge (C + D)"],
    vee: ["a \\vee b", "x \\vee y", "(A + B) \\vee (C + D)"],
    land: ["\\land", "\\land"],
    lor: ["\\lor", "\\lor"],
    lnot: ["\\lnot", "\\lnot"],
    neg: ["a \\neg b", "x \\neg y", "A \\neg B"],
    barwedge: ["\\barwedge", "\\barwedge"],
    veebar: ["\\veebar", "\\veebar"],
    doublebarwedge: ["\\doublebarwedge", "\\doublebarwedge"],
    curlyvee: ["\\curlyvee", "\\curlyvee"],
    curlywedge: ["\\curlywedge", "\\curlywedge"],
    cap: ["a \\cap b", "x \\cap y", "(A + B) \\cap (C + D)"],
    cup: ["a \\cup b", "x \\cup y", "(A + B) \\cup (C + D)"],
    Cap: ["\\Cap", "\\Cap"],
    Cup: ["\\Cup", "\\Cup"],
    sqcap: ["\\sqcap", "\\sqcap"],
    sqcup: ["\\sqcup", "\\sqcup"],
    uplus: ["\\uplus", "\\uplus"],
    setminus: ["a \\setminus b", "x \\setminus y", "(A + B) \\setminus (C + D)"],
    smallsetminus: ["\\smallsetminus", "\\smallsetminus"],
    ltimes: ["\\ltimes", "\\ltimes"],
    rtimes: ["\\rtimes", "\\rtimes"],
    leftthreetimes: ["\\leftthreetimes", "\\leftthreetimes"],
    rightthreetimes: ["\\rightthreetimes", "\\rightthreetimes"],
    divideontimes: ["\\divideontimes", "\\divideontimes"],
    dotplus: ["\\dotplus", "\\dotplus"],
    dagger: ["a \\dagger b", "x \\dagger y", "(A + B) \\dagger (C + D)"],
    ddagger: ["a \\ddagger b", "x \\ddagger y", "(A + B) \\ddagger (C + D)"],
    dag: ["a \\dag b", "x \\dag y", "(A + B) \\dag (C + D)"],
    ddag: ["a \\ddag b", "x \\ddag y", "(A + B) \\ddag (C + D)"],
    amalg: ["a \\amalg b", "x \\amalg y", "(A + B) \\amalg (C + D)"],
    wr: ["a \\wr b", "x \\wr y", "(A + B) \\wr (C + D)"],
    bigtriangleup: ["\\bigtriangleup", "\\bigtriangleup"],
    bigtriangledown: ["\\bigtriangledown", "\\bigtriangledown"],
    lhd: ["\\lhd", "\\lhd"],
    rhd: ["\\rhd", "\\rhd"],
    unlhd: ["\\unlhd", "\\unlhd"],
    unrhd: ["\\unrhd", "\\unrhd"],
    sum: ["\\sum a", "\\sum_{i=1}^n x_i", "\\sum_{i=1}^n \\sum_{j=1}^m a_{ij} x_i y_j", "\\sum_{k=0}^{\\infty} \\frac{(-1)^k x^{2k+1}}{(2k+1)!}"],
    prod: ["\\prod a", "\\prod_{i=1}^n x_i", "\\prod_{p \\text{ prime}} \\frac{1}{1 - p^{-s}} = \\zeta(s)"],
    coprod: ["\\coprod a", "\\coprod_{i \\in I} X_i"],
    int: ["\\int a dx", "\\int_{a}^{b} f(x) dx", "\\int_{-\\infty}^{\\infty} e^{-x^2} dx = \\sqrt{\\pi}", "\\int_{0}^{1} \\int_{0}^{1-x} f(x, y) dy dx"],
    integral: ["\\int a dx", "\\int_{a}^{b} f(x) dx", "\\int_{-\\infty}^{\\infty} e^{-x^2} dx = \\sqrt{\\pi}", "\\int_{0}^{1} \\int_{0}^{1-x} f(x, y) dy dx"],
    iint: ["\\iint a dx dy", "\\iint_D (x^2 + y^2) dx dy"],
    iiint: ["\\iiint a dx dy dz", "\\iiint_V f(x,y,z) dx dy dz"],
    iiiint: ["\\iiiint a", "\\iiiint_{i=1}^n x_i", "\\iiiint_{k=0}^{\\infty} (a_k + b_k)"],
    oint: ["\\oint a dx", "\\oint_C \\vec{F} \\cdot d\\vec{r}", "\\oint_{\\partial \\Omega} (P dx + Q dy) = \\iint_{\\Omega} \\left( \\frac{\\partial Q}{\\partial x} - \\frac{\\partial P}{\\partial y} \\right) dx dy"],
    oiint: ["\\oiint a dA", "\\oiint_S \\vec{E} \\cdot d\\vec{A} = \\frac{Q_{\\text{encl}}}{\\varepsilon_0}"],
    oiiint: ["\\oiiint a", "\\oiiint_{i=1}^n x_i", "\\oiiint_{k=0}^{\\infty} (a_k + b_k)"],
    intop: ["\\intop", "\\intop"],
    smallint: ["\\smallint", "\\smallint"],
    ointctrclockwise: ["\\ointctrclockwise", "\\ointctrclockwise"],
    ointclockwise: ["\\ointclockwise", "\\ointclockwise"],
    bigvee: ["\\bigvee a", "\\bigvee_{i=1}^n x_i", "\\bigvee_{k=0}^{\\infty} (a_k + b_k)"],
    bigwedge: ["\\bigwedge a", "\\bigwedge_{i=1}^n x_i", "\\bigwedge_{k=0}^{\\infty} (a_k + b_k)"],
    bigcup: ["\\bigcup a", "\\bigcup_{i=1}^n x_i", "\\bigcup_{k=0}^{\\infty} (a_k + b_k)"],
    bigcap: ["\\bigcap a", "\\bigcap_{i=1}^n x_i", "\\bigcap_{k=0}^{\\infty} (a_k + b_k)"],
    bigoplus: ["\\bigoplus a", "\\bigoplus_{i=1}^n x_i", "\\bigoplus_{k=0}^{\\infty} (a_k + b_k)"],
    bigotimes: ["\\bigotimes a", "\\bigotimes_{i=1}^n x_i", "\\bigotimes_{k=0}^{\\infty} (a_k + b_k)"],
    bigodot: ["\\bigodot", "\\bigodot"],
    bigsqcup: ["\\bigsqcup a", "\\bigsqcup_{i=1}^n x_i", "\\bigsqcup_{k=0}^{\\infty} (a_k + b_k)"],
    bigsqcap: ["\\bigsqcap", "\\bigsqcap"],
    biguplus: ["\\biguplus a", "\\biguplus_{i=1}^n x_i", "\\biguplus_{k=0}^{\\infty} (a_k + b_k)"],
    leq: ["a \\leq b", "x + y \\leq z", "f(x) \\leq M, \\quad \\forall x \\in D"],
    geq: ["a \\geq b", "x + y \\geq z", "\\|x\\| \\geq 0"],
    neq: ["a \\neq b", "x \\neq 0", "A \\cap B \\neq \\emptyset"],
    ll: ["\\ll", "\\ll"],
    gg: ["\\gg", "\\gg"],
    lll: ["\\lll", "\\lll"],
    ggg: ["\\ggg", "\\ggg"],
    leqq: ["\\leqq", "\\leqq"],
    geqq: ["\\geqq", "\\geqq"],
    leqslant: ["\\leqslant", "\\leqslant"],
    geqslant: ["\\geqslant", "\\geqslant"],
    lessgtr: ["\\lessgtr", "\\lessgtr"],
    gtrless: ["\\gtrless", "\\gtrless"],
    lesseqgtr: ["\\lesseqgtr", "\\lesseqgtr"],
    gtreqless: ["\\gtreqless", "\\gtreqless"],
    approx: ["a \\approx b", "e \\approx 2.718", "\\sin x \\approx x - \\frac{x^3}{6}"],
    approxeq: ["a \\approxeq b", "x \\approxeq y", "A \\approxeq B"],
    sim: ["a \\sim b", "X \\sim \\mathcal{N}(\\mu, \\sigma^2)"],
    simeq: ["a \\simeq b", "x \\simeq y", "A \\simeq B"],
    equiv: ["a \\equiv b", "x \\equiv y \\pmod{m}"],
    cong: ["a \\cong b", "x \\cong y", "A \\cong B"],
    asymp: ["\\asymp", "\\asymp"],
    doteq: ["a \\doteq b", "x \\doteq y", "A \\doteq B"],
    doteqdot: ["\\doteqdot", "\\doteqdot"],
    eqcirc: ["\\eqcirc", "\\eqcirc"],
    circeq: ["a \\circeq b", "x \\circeq y", "A \\circeq B"],
    bumpeq: ["a \\bumpeq b", "x \\bumpeq y", "A \\bumpeq B"],
    Bumpeq: ["a \\Bumpeq b", "x \\Bumpeq y", "A \\Bumpeq B"],
    lesssim: ["\\lesssim", "\\lesssim"],
    gtrsim: ["\\gtrsim", "\\gtrsim"],
    lessapprox: ["\\lessapprox", "\\lessapprox"],
    gtrapprox: ["\\gtrapprox", "\\gtrapprox"],
    subset: ["a \\subset b", "x \\subset y", "A \\subset B"],
    supset: ["a \\supset b", "x \\supset y", "A \\supset B"],
    subseteq: ["a \\subseteq b", "x \\subseteq y", "A \\subseteq B"],
    supseteq: ["a \\supseteq b", "x \\supseteq y", "A \\supseteq B"],
    subseteqq: ["\\subseteqq", "\\subseteqq"],
    supseteqq: ["\\supseteqq", "\\supseteqq"],
    Subset: ["\\Subset", "\\Subset"],
    Supset: ["\\Supset", "\\Supset"],
    sqsubset: ["\\sqsubset", "\\sqsubset"],
    sqsupset: ["\\sqsupset", "\\sqsupset"],
    sqsubseteq: ["a \\sqsubseteq b", "x \\sqsubseteq y", "A \\sqsubseteq B"],
    sqsupseteq: ["a \\sqsupseteq b", "x \\sqsupseteq y", "A \\sqsupseteq B"],
    in: ["a \\in b", "x \\in y", "A \\in B"],
    notin: ["a \\notin b", "x \\notin y", "A \\notin B"],
    ni: ["a \\ni b", "x \\ni y", "A \\ni B"],
    prec: ["\\prec", "\\prec"],
    succ: ["\\succ", "\\succ"],
    preceq: ["a \\preceq b", "x \\preceq y", "A \\preceq B"],
    succeq: ["a \\succeq b", "x \\succeq y", "A \\succeq B"],
    precsim: ["\\precsim", "\\precsim"],
    succsim: ["\\succsim", "\\succsim"],
    precapprox: ["\\precapprox", "\\precapprox"],
    succapprox: ["\\succapprox", "\\succapprox"],
    preccurlyeq: ["a \\preccurlyeq b", "x \\preccurlyeq y", "A \\preccurlyeq B"],
    succcurlyeq: ["a \\succcurlyeq b", "x \\succcurlyeq y", "A \\succcurlyeq B"],
    curlyeqprec: ["\\curlyeqprec", "\\curlyeqprec"],
    curlyeqsucc: ["\\curlyeqsucc", "\\curlyeqsucc"],
    propto: ["a \\propto b", "x \\propto y", "A \\propto B"],
    varpropto: ["\\varpropto", "\\varpropto"],
    perp: ["a \\perp b", "x \\perp y", "A \\perp B"],
    mid: ["a \\mid b", "x \\mid y", "A \\mid B"],
    parallel: ["a \\parallel b", "x \\parallel y", "A \\parallel B"],
    shortmid: ["\\shortmid", "\\shortmid"],
    shortparallel: ["\\shortparallel", "\\shortparallel"],
    between: ["a \\between b", "x \\between y", "A \\between B"],
    pitchfork: ["a \\pitchfork b", "x \\pitchfork y", "A \\pitchfork B"],
    backepsilon: ["\\backepsilon", "\\backepsilon"],
    vdash: ["\\vdash", "\\vdash"],
    dashv: ["\\dashv", "\\dashv"],
    Vdash: ["\\Vdash", "\\Vdash"],
    vDash: ["\\vDash", "\\vDash"],
    Vvdash: ["\\Vvdash", "\\Vvdash"],
    models: ["\\models", "\\models"],
    smile: ["a \\smile b", "x \\smile y", "A \\smile B"],
    frown: ["a \\frown b", "x \\frown y", "A \\frown B"],
    bowtie: ["a \\bowtie b", "x \\bowtie y", "A \\bowtie B"],
    Join: ["a \\Join b", "x \\Join y", "A \\Join B"],
    triangleleft: ["\\triangleleft", "\\triangleleft"],
    triangleright: ["\\triangleright", "\\triangleright"],
    trianglelefteq: ["a \\trianglelefteq b", "x \\trianglelefteq y", "A \\trianglelefteq B"],
    trianglerighteq: ["a \\trianglerighteq b", "x \\trianglerighteq y", "A \\trianglerighteq B"],
    impliedby: ["a \\impliedby b", "x^2 > 4 \\impliedby x > 2"],
    implies: ["a \\implies b", "x > 2 \\implies x^2 > 4"],
    iff: ["a \\iff b", "A \\subseteq B \\iff (A \\cap B = A)"],
    le: ["a \\leq b", "x + y \\leq z", "f(x) \\leq M, \\quad \\forall x \\in D"],
    ge: ["a \\geq b", "x + y \\geq z", "\\|x\\| \\geq 0"],
    ne: ["a \\neq b", "x \\neq 0", "A \\cap B \\neq \\emptyset"],
    owns: ["\\owns", "\\owns"],
    nleq: ["a \\nleq b", "x \\nleq y", "A \\nleq B"],
    ngeq: ["a \\ngeq b", "x \\ngeq y", "A \\ngeq B"],
    nleqq: ["a \\nleqq b", "x \\nleqq y", "A \\nleqq B"],
    ngeqq: ["a \\ngeqq b", "x \\ngeqq y", "A \\ngeqq B"],
    nleqslant: ["a \\nleqslant b", "x \\nleqslant y", "A \\nleqslant B"],
    ngeqslant: ["a \\ngeqslant b", "x \\ngeqslant y", "A \\ngeqslant B"],
    nless: ["a \\nless b", "x \\nless y", "A \\nless B"],
    ngtr: ["a \\ngtr b", "x \\ngtr y", "A \\ngtr B"],
    nsubseteq: ["a \\nsubseteq b", "x \\nsubseteq y", "A \\nsubseteq B"],
    nsupseteq: ["a \\nsupseteq b", "x \\nsupseteq y", "A \\nsupseteq B"],
    nsubseteqq: ["a \\nsubseteqq b", "x \\nsubseteqq y", "A \\nsubseteqq B"],
    nsupseteqq: ["a \\nsupseteqq b", "x \\nsupseteqq y", "A \\nsupseteqq B"],
    subsetneq: ["a \\subsetneq b", "x \\subsetneq y", "A \\subsetneq B"],
    supsetneq: ["a \\supsetneq b", "x \\supsetneq y", "A \\supsetneq B"],
    subsetneqq: ["\\subsetneqq", "\\subsetneqq"],
    supsetneqq: ["\\supsetneqq", "\\supsetneqq"],
    nprec: ["a \\nprec b", "x \\nprec y", "A \\nprec B"],
    nsucc: ["a \\nsucc b", "x \\nsucc y", "A \\nsucc B"],
    npreceq: ["a \\npreceq b", "x \\npreceq y", "A \\npreceq B"],
    nsucceq: ["a \\nsucceq b", "x \\nsucceq y", "A \\nsucceq B"],
    precneqq: ["\\precneqq", "\\precneqq"],
    succneqq: ["\\succneqq", "\\succneqq"],
    precnsim: ["\\precnsim", "\\precnsim"],
    succnsim: ["\\succnsim", "\\succnsim"],
    ncong: ["a \\ncong b", "x \\ncong y", "A \\ncong B"],
    nsim: ["a \\nsim b", "x \\nsim y", "A \\nsim B"],
    nmid: ["a \\nmid b", "x \\nmid y", "A \\nmid B"],
    nparallel: ["a \\nparallel b", "x \\nparallel y", "A \\nparallel B"],
    nshortmid: ["a \\nshortmid b", "x \\nshortmid y", "A \\nshortmid B"],
    nshortparallel: ["a \\nshortparallel b", "x \\nshortparallel y", "A \\nshortparallel B"],
    nvdash: ["a \\nvdash b", "x \\nvdash y", "A \\nvdash B"],
    nvDash: ["a \\nvDash b", "x \\nvDash y", "A \\nvDash B"],
    nVdash: ["a \\nVdash b", "x \\nVdash y", "A \\nVdash B"],
    nVDash: ["a \\nVDash b", "x \\nVDash y", "A \\nVDash B"],
    ntriangleleft: ["a \\ntriangleleft b", "x \\ntriangleleft y", "A \\ntriangleleft B"],
    ntriangleright: ["a \\ntriangleright b", "x \\ntriangleright y", "A \\ntriangleright B"],
    ntrianglelefteq: ["a \\ntrianglelefteq b", "x \\ntrianglelefteq y", "A \\ntrianglelefteq B"],
    ntrianglerighteq: ["a \\ntrianglerighteq b", "x \\ntrianglerighteq y", "A \\ntrianglerighteq B"],
    coloneq: ["a \\coloneq b", "x \\coloneq y", "A \\coloneq B"],
    Coloneq: ["a \\Coloneq b", "x \\Coloneq y", "A \\Coloneq B"],
    coloneqq: ["a \\coloneqq b", "x \\coloneqq y", "A \\coloneqq B"],
    Coloneqq: ["a \\Coloneqq b", "x \\Coloneqq y", "A \\Coloneqq B"],
    eqcolon: ["a \\eqcolon b", "x \\eqcolon y", "A \\eqcolon B"],
    Eqcolon: ["a \\Eqcolon b", "x \\Eqcolon y", "A \\Eqcolon B"],
    colonapprox: ["\\colonapprox", "\\colonapprox"],
    Colonapprox: ["\\Colonapprox", "\\Colonapprox"],
    colonsim: ["\\colonsim", "\\colonsim"],
    Colonsim: ["\\Colonsim", "\\Colonsim"],
    ratio: ["a \\ratio b", "x \\ratio y", "A \\ratio B"],
    coloncolon: ["a \\coloncolon b", "x \\coloncolon y", "A \\coloncolon B"],
    coloncoloneq: ["a \\coloncoloneq b", "x \\coloncoloneq y", "A \\coloncoloneq B"],
    coloncoloneqq: ["\\coloncoloneqq", "\\coloncoloneqq"],
    equalscolon: ["\\equalscolon", "\\equalscolon"],
    equalscoloncolon: ["\\equalscoloncolon", "\\equalscoloncolon"],
    rightarrow: ["a \\rightarrow b", "f: A \\to B", "x_n \\to x \\text{ as } n \\to \\infty"],
    leftarrow: ["a \\leftarrow b", "x \\leftarrow y + 1"],
    Rightarrow: ["a \\Rightarrow b", "x \\Rightarrow y", "f(x) \\Rightarrow g(y)"],
    Leftarrow: ["a \\Leftarrow b", "x \\Leftarrow y", "f(x) \\Leftarrow g(y)"],
    leftrightarrow: ["a \\leftrightarrow b", "x \\leftrightarrow y", "f(x) \\leftrightarrow g(y)"],
    Leftrightarrow: ["a \\Leftrightarrow b", "x \\Leftrightarrow y", "f(x) \\Leftrightarrow g(y)"],
    uparrow: ["a \\uparrow b", "x \\uparrow y", "f(x) \\uparrow g(y)"],
    downarrow: ["a \\downarrow b", "x \\downarrow y", "f(x) \\downarrow g(y)"],
    Uparrow: ["a \\Uparrow b", "x \\Uparrow y", "f(x) \\Uparrow g(y)"],
    Downarrow: ["a \\Downarrow b", "x \\Downarrow y", "f(x) \\Downarrow g(y)"],
    updownarrow: ["a \\updownarrow b", "x \\updownarrow y", "f(x) \\updownarrow g(y)"],
    Updownarrow: ["a \\Updownarrow b", "x \\Updownarrow y", "f(x) \\Updownarrow g(y)"],
    to: ["a \\rightarrow b", "f: A \\to B", "x_n \\to x \\text{ as } n \\to \\infty"],
    gets: ["a \\leftarrow b", "x \\leftarrow y + 1"],
    mapsto: ["a \\mapsto b", "x \\mapsto x^2 + 1"],
    nearrow: ["a \\nearrow b", "x \\nearrow y", "A \\nearrow B"],
    searrow: ["a \\searrow b", "x \\searrow y", "f(x) \\searrow g(y)"],
    nwarrow: ["a \\nwarrow b", "x \\nwarrow y", "A \\nwarrow B"],
    swarrow: ["a \\swarrow b", "x \\swarrow y", "f(x) \\swarrow g(y)"],
    rightharpoonup: ["\\rightharpoonup", "\\rightharpoonup"],
    rightharpoondown: ["\\rightharpoondown", "\\rightharpoondown"],
    leftharpoonup: ["\\leftharpoonup", "\\leftharpoonup"],
    leftharpoondown: ["\\leftharpoondown", "\\leftharpoondown"],
    upharpoonright: ["\\upharpoonright", "\\upharpoonright"],
    upharpoonleft: ["\\upharpoonleft", "\\upharpoonleft"],
    downharpoonright: ["\\downharpoonright", "\\downharpoonright"],
    downharpoonleft: ["\\downharpoonleft", "\\downharpoonleft"],
    rightleftharpoons: ["\\rightleftharpoons", "\\rightleftharpoons"],
    leftrightharpoons: ["\\leftrightharpoons", "\\leftrightharpoons"],
    hookrightarrow: ["a \\hookrightarrow b", "x \\hookrightarrow y", "f(x) \\hookrightarrow g(y)"],
    hookleftarrow: ["a \\hookleftarrow b", "x \\hookleftarrow y", "f(x) \\hookleftarrow g(y)"],
    longrightarrow: ["a \\longrightarrow b", "x \\longrightarrow y", "f(x) \\longrightarrow g(y)"],
    longleftarrow: ["a \\longleftarrow b", "x \\longleftarrow y", "f(x) \\longleftarrow g(y)"],
    longleftrightarrow: ["a \\longleftrightarrow b", "x \\longleftrightarrow y", "f(x) \\longleftrightarrow g(y)"],
    Longrightarrow: ["a \\Longrightarrow b", "x \\Longrightarrow y", "f(x) \\Longrightarrow g(y)"],
    Longleftarrow: ["a \\Longleftarrow b", "x \\Longleftarrow y", "f(x) \\Longleftarrow g(y)"],
    Longleftrightarrow: ["a \\Longleftrightarrow b", "x \\Longleftrightarrow y", "f(x) \\Longleftrightarrow g(y)"],
    longmapsto: ["\\longmapsto", "\\longmapsto"],
    twoheadrightarrow: ["a \\twoheadrightarrow b", "x \\twoheadrightarrow y", "f(x) \\twoheadrightarrow g(y)"],
    twoheadleftarrow: ["a \\twoheadleftarrow b", "x \\twoheadleftarrow y", "f(x) \\twoheadleftarrow g(y)"],
    rightarrowtail: ["\\rightarrowtail", "\\rightarrowtail"],
    leftarrowtail: ["\\leftarrowtail", "\\leftarrowtail"],
    looparrowright: ["a \\looparrowright b", "x \\looparrowright y", "f(x) \\looparrowright g(y)"],
    looparrowleft: ["a \\looparrowleft b", "x \\looparrowleft y", "f(x) \\looparrowleft g(y)"],
    curvearrowright: ["a \\curvearrowright b", "x \\curvearrowright y", "f(x) \\curvearrowright g(y)"],
    curvearrowleft: ["a \\curvearrowleft b", "x \\curvearrowleft y", "f(x) \\curvearrowleft g(y)"],
    circlearrowright: ["a \\circlearrowright b", "x \\circlearrowright y", "f(x) \\circlearrowright g(y)"],
    circlearrowleft: ["a \\circlearrowleft b", "x \\circlearrowleft y", "f(x) \\circlearrowleft g(y)"],
    dashrightarrow: ["a \\dashrightarrow b", "x \\dashrightarrow y", "f(x) \\dashrightarrow g(y)"],
    dashleftarrow: ["a \\dashleftarrow b", "x \\dashleftarrow y", "f(x) \\dashleftarrow g(y)"],
    rightsquigarrow: ["a \\rightsquigarrow b", "x \\rightsquigarrow y", "f(x) \\rightsquigarrow g(y)"],
    leftrightsquigarrow: ["a \\leftrightsquigarrow b", "x \\leftrightsquigarrow y", "f(x) \\leftrightsquigarrow g(y)"],
    leadsto: ["a \\leadsto b", "x \\leadsto y", "f(x) \\leadsto g(y)"],
    multimap: ["a \\multimap b", "x \\multimap y", "f(x) \\multimap g(y)"],
    nrightarrow: ["a \\nrightarrow b", "x \\nrightarrow y", "A \\nrightarrow B"],
    nleftarrow: ["a \\nleftarrow b", "x \\nleftarrow y", "A \\nleftarrow B"],
    nRightarrow: ["a \\nRightarrow b", "x \\nRightarrow y", "A \\nRightarrow B"],
    nLeftarrow: ["a \\nLeftarrow b", "x \\nLeftarrow y", "A \\nLeftarrow B"],
    nleftrightarrow: ["a \\nleftrightarrow b", "x \\nleftrightarrow y", "A \\nleftrightarrow B"],
    nLeftrightarrow: ["a \\nLeftrightarrow b", "x \\nLeftrightarrow y", "A \\nLeftrightarrow B"],
    sin: ["\\sin(a)", "\\sin(x + y) = \\sin x \\cos y + \\cos x \\sin y"],
    cos: ["\\cos(a)", "\\cos(x + y) = \\cos x \\cos y - \\sin x \\sin y"],
    tan: ["\\tan(a)", "\\tan(x + y) = \\frac{\\tan x + \\tan y}{1 - \\tan x \\tan y}"],
    cot: ["\\cot(a)", "\\cot(x + y)"],
    sec: ["\\sec(a)", "\\sec(x + y)"],
    csc: ["\\csc(a)", "\\csc(x + y)"],
    arcsin: ["\\arcsin(a)", "\\arcsin(x + y)"],
    arccos: ["\\arccos(a)", "\\arccos(x + y)"],
    arctan: ["\\arctan(a)", "\\arctan(x + y)"],
    arccot: ["\\arccot", "\\arccot"],
    arcsec: ["\\arcsec", "\\arcsec"],
    arccsc: ["\\arccsc", "\\arccsc"],
    sinh: ["\\sinh(a)", "\\sinh(x + y)"],
    cosh: ["\\cosh(a)", "\\cosh(x + y)"],
    tanh: ["\\tanh(a)", "\\tanh(x + y)"],
    coth: ["\\coth", "\\coth"],
    sech: ["\\sech", "\\sech"],
    csch: ["\\csch", "\\csch"],
    log: ["\\log(a)", "\\log(x y) = \\log x + \\log y", "\\log_b(a) = \\frac{\\ln a}{\\ln b}"],
    ln: ["\\ln(a)", "\\ln(x y) = \\ln x + \\ln y", "\\int \\frac{1}{x} dx = \\ln|x| + C"],
    lg: ["\\lg(a)", "\\lg(x + y)"],
    exp: ["\\exp(a)", "\\exp(i \\theta) = \\cos \\theta + i \\sin \\theta"],
    lim: ["\\lim a", "\\lim_{x \\to 0} \\frac{\\sin x}{x} = 1", "\\lim_{n \\to \\infty} \\left( 1 + \\frac{x}{n} \\right)^n = e^x"],
    limsup: ["\\limsup", "\\limsup"],
    liminf: ["\\liminf", "\\liminf"],
    varlimsup: ["\\varlimsup", "\\varlimsup"],
    varliminf: ["\\varliminf", "\\varliminf"],
    max: ["\\max(a, b)", "\\max_{x \\in [0, 1]} f(x)"],
    min: ["\\min(a, b)", "\\min_{x \\in [0, 1]} f(x)"],
    sup: ["\\sup a", "\\sup_{x \\in A} f(x)"],
    inf: ["\\inf a", "\\inf_{x \\in A} f(x)"],
    argmax: ["\\arg\\max a", "\\arg\\max_{\\theta \\in \\Theta} L(\\theta; X)"],
    argmin: ["\\arg\\min a", "\\arg\\min_{w} \\sum_{i=1}^n (y_i - w^T x_i)^2 + \\lambda |w|^2"],
    det: ["\\det(A)", "\\det \\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix} = ad - bc", "\\det(A - \\lambda I) = 0"],
    deg: ["\\deg(a)", "\\deg(x + y)"],
    gcd: ["\\gcd(a)", "\\gcd(x + y)"],
    lcm: ["\\lcm(a)", "\\lcm(x + y)"],
    ker: ["\\ker(a)", "\\ker(x + y)"],
    hom: ["\\hom(a)", "\\hom(x + y)"],
    dim: ["\\dim(a)", "\\dim(x + y)"],
    arg: ["\\arg(a)", "\\arg(x + y)"],
    Pr: ["\\Pr", "\\Pr"],
    tr: ["\\tr", "\\tr"],
    rank: ["\\rank", "\\rank"],
    span: ["\\span", "\\span"],
    sgn: ["\\sgn", "\\sgn"],
    diag: ["\\diag", "\\diag"],
    injlim: ["\\injlim", "\\injlim"],
    projlim: ["\\projlim", "\\projlim"],
    varinjlim: ["\\varinjlim", "\\varinjlim"],
    varprojlim: ["\\varprojlim", "\\varprojlim"],
    bmod: ["\\bmod", "\\bmod"],
    pmod: ["\\pmod{a}", "\\pmod{x_1 + x_2}"],
    mod: ["\\mod{a}", "\\mod{x_1 + x_2}"],
    pod: ["\\pod{a}", "\\pod{x_1 + x_2}"],
    left: ["\\left( a \\right)", "\\left( x + y \\right)"],
    right: ["\\left( a \\right)", "\\left( x + y \\right)"],
    middle: ["\\middle", "\\middle"],
    langle: ["\\left\\langle a \\right\\rangle", "\\left\\langle x + y \\right\\rangle"],
    rangle: ["\\left\\langle a \\right\\rangle", "\\left\\langle x + y \\right\\rangle"],
    lfloor: ["\\left\\lfloor a \\right\\rfloor", "\\left\\lfloor x + y \\right\\rfloor"],
    rfloor: ["\\left\\lfloor a \\right\\rfloor", "\\left\\lfloor x + y \\right\\rfloor"],
    lceil: ["\\left\\lceil a \\right\\rceil", "\\left\\lceil x + y \\right\\rceil"],
    rceil: ["\\left\\lceil a \\right\\rceil", "\\left\\lceil x + y \\right\\rceil"],
    vert: ["\\left\\vert a \\right\\vert", "\\left\\vert x + y \\right\\vert"],
    Vert: ["\\left\\Vert a \\right\\Vert", "\\left\\Vert x + y \\right\\Vert"],
    lvert: ["\\left\\lvert a \\right\\rvert", "\\left\\lvert x + y \\right\\rvert"],
    rvert: ["\\left\\lvert a \\right\\rvert", "\\left\\lvert x + y \\right\\rvert"],
    lVert: ["\\left\\lVert a \\right\\rVert", "\\left\\lVert x + y \\right\\rVert"],
    rVert: ["\\left\\lVert a \\right\\rVert", "\\left\\lVert x + y \\right\\rVert"],
    ulcorner: ["\\ulcorner", "\\ulcorner"],
    urcorner: ["\\urcorner", "\\urcorner"],
    llcorner: ["\\llcorner", "\\llcorner"],
    lrcorner: ["\\lrcorner", "\\lrcorner"],
    infty: ["\\infty", "\\infty"],
    partial: ["\\partial", "\\partial"],
    nabla: ["a \\nabla b", "x \\nabla y", "A \\nabla B"],
    forall: ["\\forall", "\\forall"],
    exists: ["\\exists", "\\exists"],
    nexists: ["a \\nexists b", "x \\nexists y", "A \\nexists B"],
    not: ["a \\not b", "x \\not y", "A \\not B"],
    top: ["\\top", "\\top"],
    bot: ["\\bot", "\\bot"],
    emptyset: ["\\emptyset", "\\emptyset"],
    varnothing: ["\\varnothing", "\\varnothing"],
    ldots: ["\\ldots", "\\ldots"],
    cdots: ["\\cdots", "\\cdots"],
    vdots: ["\\vdots", "\\vdots"],
    ddots: ["\\ddots", "\\ddots"],
    hdots: ["\\hdots", "\\hdots"],
    iddots: ["\\iddots", "\\iddots"],
    dots: ["\\dots", "\\dots"],
    dotsb: ["\\dotsb", "\\dotsb"],
    dotsc: ["\\dotsc", "\\dotsc"],
    dotsi: ["\\dotsi", "\\dotsi"],
    dotsm: ["\\dotsm", "\\dotsm"],
    dotso: ["\\dotso", "\\dotso"],
    aleph: ["\\aleph", "\\aleph"],
    beth: ["\\beth", "\\beth"],
    gimel: ["\\gimel", "\\gimel"],
    daleth: ["\\daleth", "\\daleth"],
    hbar: ["\\hbar", "\\hbar"],
    hslash: ["\\hslash", "\\hslash"],
    ell: ["\\ell", "\\ell"],
    imath: ["\\imath", "\\imath"],
    jmath: ["\\jmath", "\\jmath"],
    Re: ["\\Re", "\\Re"],
    Im: ["\\Im", "\\Im"],
    wp: ["\\wp", "\\wp"],
    complement: ["\\complement", "\\complement"],
    Finv: ["\\Finv", "\\Finv"],
    Game: ["\\Game", "\\Game"],
    mho: ["\\mho", "\\mho"],
    eth: ["\\eth", "\\eth"],
    prime: ["\\prime", "\\prime"],
    backprime: ["\\backprime", "\\backprime"],
    backslash: ["\\backslash", "\\backslash"],
    diagup: ["\\diagup", "\\diagup"],
    diagdown: ["\\diagdown", "\\diagdown"],
    therefore: ["\\therefore", "\\therefore"],
    because: ["\\because", "\\because"],
    angle: ["\\angle", "\\angle"],
    measuredangle: ["\\measuredangle", "\\measuredangle"],
    sphericalangle: ["\\sphericalangle", "\\sphericalangle"],
    triangle: ["\\triangle", "\\triangle"],
    blacktriangle: ["\\blacktriangle", "\\blacktriangle"],
    blacktriangledown: ["\\blacktriangledown", "\\blacktriangledown"],
    blacktriangleleft: ["\\blacktriangleleft", "\\blacktriangleleft"],
    blacktriangleright: ["\\blacktriangleright", "\\blacktriangleright"],
    degree: ["\\degree", "\\degree"],
    square: ["\\square", "\\square"],
    blacksquare: ["\\blacksquare", "\\blacksquare"],
    lozenge: ["\\lozenge", "\\lozenge"],
    blacklozenge: ["\\blacklozenge", "\\blacklozenge"],
    bigstar: ["\\bigstar", "\\bigstar"],
    circledR: ["a \\circledR b", "x \\circledR y", "(A + B) \\circledR (C + D)"],
    circledS: ["a \\circledS b", "x \\circledS y", "(A + B) \\circledS (C + D)"],
    flat: ["\\flat", "\\flat"],
    natural: ["a \\natural b", "x \\natural y", "A \\natural B"],
    sharp: ["\\sharp", "\\sharp"],
    clubsuit: ["\\clubsuit", "\\clubsuit"],
    diamondsuit: ["\\diamondsuit", "\\diamondsuit"],
    heartsuit: ["\\heartsuit", "\\heartsuit"],
    spadesuit: ["\\spadesuit", "\\spadesuit"],
    S: ["\\S", "\\S"],
    P: ["\\P", "\\P"],
    copyright: ["\\copyright", "\\copyright"],
    pounds: ["\\pounds", "\\pounds"],
    yen: ["\\yen", "\\yen"],
    checkmark: ["\\checkmark", "\\checkmark"],
    maltese: ["\\maltese", "\\maltese"],
    llbracket: ["\\left\\llbracket a \\right\\rlbracket", "\\left\\llbracket x + y \\right\\rlbracket"],
    rrbracket: ["\\left\\lrbracket a \\right\\rrbracket", "\\left\\lrbracket x + y \\right\\rrbracket"],
    lgroup: ["\\left\\lgroup a \\right\\rgroup", "\\left\\lgroup x + y \\right\\rgroup"],
    rgroup: ["\\left\\lgroup a \\right\\rgroup", "\\left\\lgroup x + y \\right\\rgroup"],
    lmoustache: ["\\left\\lmoustache a \\right\\rmoustache", "\\left\\lmoustache x + y \\right\\rmoustache"],
    rmoustache: ["\\left\\lmoustache a \\right\\rmoustache", "\\left\\lmoustache x + y \\right\\rmoustache"],
    bracevert: ["\\bracevert", "\\bracevert"],
    lBrace: ["\\left\\lBrace a \\right\\rBrace", "\\left\\lBrace x + y \\right\\rBrace"],
    rBrace: ["\\left\\lBrace a \\right\\rBrace", "\\left\\lBrace x + y \\right\\rBrace"],
    cdotp: ["\\cdotp", "\\cdotp"],
    ldotp: ["\\ldotp", "\\ldotp"],
    colon: ["\\colon", "\\colon"],
    AA: ["\\AA", "\\AA"],
    ss: ["\\ss", "\\ss"],
    ae: ["\\ae", "\\ae"],
    oe: ["\\oe", "\\oe"],
    AE: ["\\AE", "\\AE"],
    OE: ["\\OE", "\\OE"],
    o: ["\\o", "\\o"],
    O: ["\\O", "\\O"],
    i: ["\\i", "\\i"],
    j: ["\\j", "\\j"],
    displaystyle: ["\\displaystyle", "\\displaystyle"],
    textstyle: ["\\textstyle", "\\textstyle"],
    scriptstyle: ["\\scriptstyle", "\\scriptstyle"],
    scriptscriptstyle: ["\\scriptscriptstyle", "\\scriptscriptstyle"],
    phantom: ["\\phantom{a}", "\\phantom{x_1 + x_2}"],
    hphantom: ["\\hphantom{a}", "\\hphantom{x_1 + x_2}"],
    vphantom: ["\\vphantom{a}", "\\vphantom{x_1 + x_2}"],
    smash: ["\\smash{a}", "\\smash{x_1 + x_2}"],
    color: ["\\color{a}", "\\color{x_1 + x_2}"],
    textcolor: ["\\textcolor{a}{b}", "\\textcolor{x + y}{z + w}"],
    colorbox: ["\\colorbox{a}{b}", "\\colorbox{x + y}{z + w}"],
    fcolorbox: ["\\fcolorbox{a}{b}{c}", "\\fcolorbox{x}{y}{z}"],
    boxed: ["\\boxed{a}", "\\boxed{x_1 + x_2}"],
    cancel: ["\\cancel{a}", "\\cancel{x_1 + x_2}"],
    bcancel: ["\\bcancel{a}", "\\bcancel{x_1 + x_2}"],
    xcancel: ["\\xcancel{a}", "\\xcancel{x_1 + x_2}"],
    sout: ["\\sout{a}", "\\sout{x_1 + x_2}"],
    operatorname: ["\\operatorname{a}", "\\operatorname{x_1 + x_2}"],
    "operatorname*": ["\\operatorname*{a}", "\\operatorname*{x_1 + x_2}"],
    tag: ["\\tag{a}", "\\tag{x_1 + x_2}"],
    "tag*": ["\\tag*{a}", "\\tag*{x_1 + x_2}"],
    substack: ["\\substack{a}", "\\substack{x_1 + x_2}"],
    limits: ["\\sum\\limits a", "\\sum\\limits_{i=1}^n x_i"],
    nolimits: ["a \\nolimits b", "x \\nolimits y", "A \\nolimits B"],
    rule: ["\\rule{a}{b}", "\\rule{x + y}{z + w}"],
    href: ["\\href{a}{b}", "\\href{x + y}{z + w}"],
    url: ["\\url{a}", "\\url{x_1 + x_2}"],
    kern: ["\\kern{a}", "\\kern{x_1 + x_2}"],
    mkern: ["\\mkern{a}", "\\mkern{x_1 + x_2}"],
    mskip: ["\\mskip{a}", "\\mskip{x_1 + x_2}"],
    laplace: ["\\laplace(a)", "\\laplace(x + y)"],
    Fourier: ["\\Fourier(a)", "\\Fourier(x + y)"],
    fourier: ["\\fourier", "\\fourier"],
    Mellin: ["\\Mellin(a)", "\\Mellin(x + y)"],
    mellin: ["\\mellin", "\\mellin"],
    "!": ["\\!", "\\!"],
    ",": ["\\,", "\\,"],
    ":": ["\\:", "\\:"],
    ";": ["\\;", "\\;"],
    " ": ["\\ ", "\\ "],
    matrix: ["\\begin{matrix} a & b \\\\ c & d \\end{matrix}", "\\begin{matrix} x_1 & y_1 & z_1 \\\\ x_2 & y_2 & z_2 \\\\ x_3 & y_3 & z_3 \\end{matrix}"],
    pmatrix: ["\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}", "\\begin{pmatrix} \\cos \\theta & -\\sin \\theta \\\\ \\sin \\theta & \\cos \\theta \\end{pmatrix}"],
    bmatrix: ["\\begin{bmatrix} a & b \\\\ c & d \\end{bmatrix}", "\\begin{bmatrix} 1 & 0 & 0 \\\\ 0 & 1 & 0 \\\\ 0 & 0 & 1 \\end{bmatrix}"],
    Bmatrix: ["\\Bmatrix{a & b \\\\ c & d}", "\\Bmatrix{x_1 & y_1 \\\\ x_2 & y_2}"],
    vmatrix: ["\\begin{vmatrix} a & b \\\\ c & d \\end{vmatrix}", "\\begin{vmatrix} a & b & c \\\\ d & e & f \\\\ g & h & i \\end{vmatrix} = a(ei - fh) - b(di - fg) + c(dh - eg)"],
    Vmatrix: ["\\begin{Vmatrix} a & b \\\\ c & d \\end{Vmatrix}"],
    cases: ["\\begin{cases} a & b \\\\ c & d \\end{cases}", "\\begin{cases} x^2 & \\text{if } x \\ge 0 \\\\ -x^2 & \\text{if } x < 0 \\end{cases}", "f(n) = \\begin{cases} n/2 & \\text{if } n \\text{ is even} \\\\ 3n+1 & \\text{if } n \\text{ is odd} \\end{cases}"],
    rcases: ["\\rcases{a & b \\\\ c & d}", "\\rcases{x_1 & y_1 \\\\ x_2 & y_2}"],
    dcases: ["\\dcases{a & b \\\\ c & d}", "\\dcases{x_1 & y_1 \\\\ x_2 & y_2}"],
    align: ["\\align{a & b \\\\ c & d}", "\\align{x_1 & y_1 \\\\ x_2 & y_2}"],
    aligned: ["\\aligned{a & b \\\\ c & d}", "\\aligned{x_1 & y_1 \\\\ x_2 & y_2}"],
    gather: ["\\gather{a & b \\\\ c & d}", "\\gather{x_1 & y_1 \\\\ x_2 & y_2}"],
    gathered: ["\\gathered{a & b \\\\ c & d}", "\\gathered{x_1 & y_1 \\\\ x_2 & y_2}"],
    split: ["\\split{a & b \\\\ c & d}", "\\split{x_1 & y_1 \\\\ x_2 & y_2}"],
    multline: ["\\multline{a & b \\\\ c & d}", "\\multline{x_1 & y_1 \\\\ x_2 & y_2}"],
    equation: ["\\equation{a & b \\\\ c & d}", "\\equation{x_1 & y_1 \\\\ x_2 & y_2}"],
    array: ["\\array{a & b \\\\ c & d}", "\\array{x_1 & y_1 \\\\ x_2 & y_2}"],
    smallmatrix: ["\\smallmatrix{a & b \\\\ c & d}", "\\smallmatrix{x_1 & y_1 \\\\ x_2 & y_2}"],
    subarray: ["\\subarray{a & b \\\\ c & d}", "\\subarray{x_1 & y_1 \\\\ x_2 & y_2}"],
    "\\": ["\\\\", "\\\\"],
};
