export const delimitersMisc = {
    ["left"]: { args: 0, optArgs: 0 },
    ["right"]: { args: 0, optArgs: 0 },
    ["langle"]: { args: 0, optArgs: 0 },
    ["rangle"]: { args: 0, optArgs: 0 },
    ["lfloor"]: { args: 0, optArgs: 0 },
    ["rfloor"]: { args: 0, optArgs: 0 },
    ["lceil"]: { args: 0, optArgs: 0 },
    ["rceil"]: { args: 0, optArgs: 0 },
    ["infty"]: { args: 0, optArgs: 0 },
    ["partial"]: { args: 0, optArgs: 0 },
    ["nabla"]: { args: 0, optArgs: 0 },
    ["forall"]: { args: 0, optArgs: 0 },
    ["exists"]: { args: 0, optArgs: 0 },
    ["nexists"]: { args: 0, optArgs: 0 },
    ["emptyset"]: { args: 0, optArgs: 0 },
    ["varnothing"]: { args: 0, optArgs: 0 },
    ["ldots"]: { args: 0, optArgs: 0 },
    ["cdots"]: { args: 0, optArgs: 0 },
    ["vdots"]: { args: 0, optArgs: 0 },
    ["ddots"]: { args: 0, optArgs: 0 },
    ["aleph"]: { args: 0, optArgs: 0 },
    ["hbar"]: { args: 0, optArgs: 0 },
    ["ell"]: { args: 0, optArgs: 0 },
    ["Re"]: { args: 0, optArgs: 0 },
    ["Im"]: { args: 0, optArgs: 0 },
    ["wp"]: { args: 0, optArgs: 0 },
    ["prime"]: { args: 0, optArgs: 0 },
    ["displaystyle"]: { args: 0, optArgs: 0 },
    ["textstyle"]: { args: 0, optArgs: 0 },
    ["scriptstyle"]: { args: 0, optArgs: 0 },
    ["not"]: { args: 0, optArgs: 0 },
    ["vert"]: { args: 0, optArgs: 0 },
    ["Vert"]: { args: 0, optArgs: 0 },
    ["backslash"]: { args: 0, optArgs: 0 },
    ["therefore"]: { args: 0, optArgs: 0 },
    ["because"]: { args: 0, optArgs: 0 },
    ["angle"]: { args: 0, optArgs: 0 },
    ["triangle"]: { args: 0, optArgs: 0 },
    ["degree"]: { args: 0, optArgs: 0 },
    ["hdots"]: { args: 0, optArgs: 0 },
    ["mho"]: { args: 0, optArgs: 0 },
    ["eth"]: { args: 0, optArgs: 0 },
    ["backprime"]: { args: 0, optArgs: 0 },
    ["diagup"]: { args: 0, optArgs: 0 },
    ["diagdown"]: { args: 0, optArgs: 0 },
    ["flat"]: { args: 0, optArgs: 0 },
    ["natural"]: { args: 0, optArgs: 0 },
    ["sharp"]: { args: 0, optArgs: 0 },
    ["clubsuit"]: { args: 0, optArgs: 0 },
    ["diamondsuit"]: { args: 0, optArgs: 0 },
    ["heartsuit"]: { args: 0, optArgs: 0 },
    ["spadesuit"]: { args: 0, optArgs: 0 },

    // Aliases
    ["hslash"]: { args: 0, optArgs: 0 }, // Alias for \hbar
};
