export const fontsSpacing = {
    ["mathrm"]: { args: 1, optArgs: 0 },
    ["mathbf"]: { args: 1, optArgs: 0 },
    ["mathit"]: { args: 1, optArgs: 0 },
    ["mathbb"]: { args: 1, optArgs: 0 },
    ["mathcal"]: { args: 1, optArgs: 0 },
    ["mathfrak"]: { args: 1, optArgs: 0 },
    ["mathsf"]: { args: 1, optArgs: 0 },
    ["mathtt"]: { args: 1, optArgs: 0 },
    ["text"]: { args: 1, optArgs: 0 },
    ["mbox"]: { args: 1, optArgs: 0 },
    ["mathnormal"]: { args: 1, optArgs: 0 },
    ["boldsymbol"]: { args: 1, optArgs: 0 },
    ["mathbfit"]: { args: 1, optArgs: 0 },
    ["mathsfit"]: { args: 1, optArgs: 0 },
    ["mathbfsfit"]: { args: 1, optArgs: 0 },
    ["scr"]: { args: 1, optArgs: 0 },
    ["quad"]: { args: 0, optArgs: 0 },
    ["qquad"]: { args: 0, optArgs: 0 },
    ["hspace"]: { args: 1, optArgs: 0 },
    ["vspace"]: { args: 1, optArgs: 0 },
};
