export const greek = {
    // Lowercase Greek letters
    ["alpha"]: { args: 0, optArgs: 0 },
    ["beta"]: { args: 0, optArgs: 0 },
    ["gamma"]: { args: 0, optArgs: 0 },
    ["delta"]: { args: 0, optArgs: 0 },
    ["epsilon"]: { args: 0, optArgs: 0 },
    ["zeta"]: { args: 0, optArgs: 0 },
    ["eta"]: { args: 0, optArgs: 0 },
    ["theta"]: { args: 0, optArgs: 0 },
    ["iota"]: { args: 0, optArgs: 0 },
    ["kappa"]: { args: 0, optArgs: 0 },
    ["lambda"]: { args: 0, optArgs: 0 },
    ["mu"]: { args: 0, optArgs: 0 },
    ["nu"]: { args: 0, optArgs: 0 },
    ["xi"]: { args: 0, optArgs: 0 },
    ["pi"]: { args: 0, optArgs: 0 },
    ["rho"]: { args: 0, optArgs: 0 },
    ["varrho"]: { args: 0, optArgs: 0 },
    ["sigma"]: { args: 0, optArgs: 0 },
    ["tau"]: { args: 0, optArgs: 0 },
    ["upsilon"]: { args: 0, optArgs: 0 },
    ["phi"]: { args: 0, optArgs: 0 },
    ["chi"]: { args: 0, optArgs: 0 },
    ["psi"]: { args: 0, optArgs: 0 },
    ["omega"]: { args: 0, optArgs: 0 },

    // Uppercase Greek letters
    ["Alpha"]: { args: 0, optArgs: 0 },
    ["Beta"]: { args: 0, optArgs: 0 },
    ["Gamma"]: { args: 0, optArgs: 0 },
    ["Delta"]: { args: 0, optArgs: 0 },
    ["Epsilon"]: { args: 0, optArgs: 0 },
    ["Zeta"]: { args: 0, optArgs: 0 },
    ["Eta"]: { args: 0, optArgs: 0 },
    ["Theta"]: { args: 0, optArgs: 0 },
    ["Iota"]: { args: 0, optArgs: 0 },
    ["Kappa"]: { args: 0, optArgs: 0 },
    ["Lambda"]: { args: 0, optArgs: 0 },
    ["Mu"]: { args: 0, optArgs: 0 },
    ["Nu"]: { args: 0, optArgs: 0 },
    ["Xi"]: { args: 0, optArgs: 0 },
    ["Pi"]: { args: 0, optArgs: 0 },
    ["Rho"]: { args: 0, optArgs: 0 },
    ["Sigma"]: { args: 0, optArgs: 0 },
    ["Tau"]: { args: 0, optArgs: 0 },
    ["Upsilon"]: { args: 0, optArgs: 0 },
    ["Phi"]: { args: 0, optArgs: 0 },
    ["Chi"]: { args: 0, optArgs: 0 },
    ["Psi"]: { args: 0, optArgs: 0 },
    ["Omega"]: { args: 0, optArgs: 0 },

    // Lowercase Greek variants
    ["varbeta"]: { args: 0, optArgs: 0 },
    ["varepsilon"]: { args: 0, optArgs: 0 },
    ["vartheta"]: { args: 0, optArgs: 0 },
    ["varkappa"]: { args: 0, optArgs: 0 },
    ["varpi"]: { args: 0, optArgs: 0 },
    ["varsigma"]: { args: 0, optArgs: 0 },
    ["varphi"]: { args: 0, optArgs: 0 },
    ["digamma"]: { args: 0, optArgs: 0 },

    // Uppercase Greek variants
    ["Digamma"]: { args: 0, optArgs: 0 },
};
