export const operators = {
    ["pm"]: { args: 0, optArgs: 0 },
    ["mp"]: { args: 0, optArgs: 0 },
    ["times"]: { args: 0, optArgs: 0 },
    ["div"]: { args: 0, optArgs: 0 },
    ["cdot"]: { args: 0, optArgs: 0 },
    ["ast"]: { args: 0, optArgs: 0 },
    ["star"]: { args: 0, optArgs: 0 },
    ["circ"]: { args: 0, optArgs: 0 },
    ["bullet"]: { args: 0, optArgs: 0 },
    ["oplus"]: { args: 0, optArgs: 0 },
    ["ominus"]: { args: 0, optArgs: 0 },
    ["otimes"]: { args: 0, optArgs: 0 },
    ["oslash"]: { args: 0, optArgs: 0 },
    ["wedge"]: { args: 0, optArgs: 0 },
    ["vee"]: { args: 0, optArgs: 0 },
    ["cap"]: { args: 0, optArgs: 0 },
    ["cup"]: { args: 0, optArgs: 0 },
    ["setminus"]: { args: 0, optArgs: 0 },
    ["box"]: { args: 0, optArgs: 0 },
    ["divideontimes"]: { args: 0, optArgs: 0 },
    ["dotplus"]: { args: 0, optArgs: 0 },
    ["doublebarwedge"]: { args: 0, optArgs: 0 },
    ["leftthreetimes"]: { args: 0, optArgs: 0 },
    ["rightthreetimes"]: { args: 0, optArgs: 0 },
    ["barwedge"]: { args: 0, optArgs: 0 },
    ["curlyvee"]: { args: 0, optArgs: 0 },
    ["curlywedge"]: { args: 0, optArgs: 0 },
    ["Cap"]: { args: 0, optArgs: 0 },
    ["Cup"]: { args: 0, optArgs: 0 },

    // Logical operator aliases
    ["land"]: { args: 0, optArgs: 0 }, // Alias for \wedge
    ["lor"]: { args: 0, optArgs: 0 }, // Alias for \vee
    ["lnot"]: { args: 0, optArgs: 0 }, // Alias for \neg
    ["neg"]: { args: 0, optArgs: 0 },

    // Large operators
    ["sum"]: { args: 0, optArgs: 0 },
    ["prod"]: { args: 0, optArgs: 0 },
    ["coprod"]: { args: 0, optArgs: 0 },
    ["int"]: { args: 0, optArgs: 0 },
    ["integral"]: { args: 0, optArgs: 0 },
    ["iint"]: { args: 0, optArgs: 0 },
    ["iiint"]: { args: 0, optArgs: 0 },
    ["iiiint"]: { args: 0, optArgs: 0 },
    ["oint"]: { args: 0, optArgs: 0 },
    ["oiint"]: { args: 0, optArgs: 0 },
    ["oiiint"]: { args: 0, optArgs: 0 },
    ["ointctrclockwise"]: { args: 0, optArgs: 0 },
    ["ointclockwise"]: { args: 0, optArgs: 0 },
    ["bigvee"]: { args: 0, optArgs: 0 },
    ["bigcup"]: { args: 0, optArgs: 0 },
    ["bigcap"]: { args: 0, optArgs: 0 },
    ["bigoplus"]: { args: 0, optArgs: 0 },
    ["bigotimes"]: { args: 0, optArgs: 0 },
    ["bigsqcup"]: { args: 0, optArgs: 0 },
    ["bigwedge"]: { args: 0, optArgs: 0 },
};
