const trigonometricFunctions = {
    sin: "sin",
    cos: "cos",
    tan: "tan",
    cot: "cot",
    sec: "sec",
    csc: "csc",
    arcsin: "arcsin",
    arccos: "arccos",
    arctan: "arctan",
    arccot: "arccot",
    arcsec: "arcsec",
    arccsc: "arccsc",
    sinh: "sinh",
    cosh: "cosh",
    tanh: "tanh",
    coth: "coth",
    sech: "sech",
    csch: "csch",
};

const logarithmicFunctions = {
    log: "log",
    ln: "ln",
    lg: "lg",
    exp: "exp",
};

const namedLimitFunctions = {
    lim: "lim",
    limsup: "lim sup",
    liminf: "lim inf",
    varlimsup: "lim sup",
    varliminf: "lim inf",
};

const algebraFunctions = {
    max: "max",
    min: "min",
    sup: "sup",
    inf: "inf",
    argmax: "arg max",
    argmin: "arg min",
    det: "det",
    deg: "deg",
    gcd: "gcd",
    lcm: "lcm",
    ker: "ker",
    hom: "hom",
    dim: "dim",
    arg: "arg",
    Pr: "Pr",
    tr: "tr",
    rank: "rank",
    span: "span",
    sgn: "sgn",
    diag: "diag",
};

const directedLimitFunctions = {
    injlim: "inj lim",
    projlim: "proj lim",
    varinjlim: "inj lim",
    varprojlim: "proj lim",
};

const relationFunctionSymbols = {
    bmod: "mod",
    lesseqgtr: "⋚",
    gtreqless: "⋛",
    eqcirc: "≖",
    circeq: "≗",
    bumpeq: "≎",
    Bumpeq: "≏",
    lessapprox: "⪅",
    gtrapprox: "⪆",
    precapprox: "⪷",
    succapprox: "⪸",
    varpropto: "∝",
    backepsilon: "∍",
    vDash: "⊨",
    Vvdash: "⊩",
    smile: "⌣",
    frown: "⌢",
    bowtie: "⋈",
    Join: "⋈",
    nleqq: "≨̸",
    ngeqq: "≩̸",
    nleqslant: "⩽̸",
    ngeqslant: "⩾̸",
    nless: "≮",
    ngtr: "≯",
    nsubseteqq: "⫅̸",
    nsupseteqq: "⫆̸",
    precneqq: "⪵",
    succneqq: "⪶",
    precnsim: "⋠",
    succnsim: "⋡",
    nshortmid: "∤",
    nshortparallel: "∦",
    nvdash: "⊬",
    nvDash: "⊭",
    nVdash: "⊮",
    nVDash: "⊯",
    colonapprox: "∷≈",
    Colonapprox: "∷≈",
    colonsim: "∷∼",
    Colonsim: "∷∼",
    ratio: ":",
    coloncoloneq: "∷=",
    coloncoloneqq: "∷=",
    equalscolon: "==",
    equalscoloncolon: "==∷",
};

const arrowFunctionSymbols = {
    upharpoonright: "↾",
    upharpoonleft: "↿",
    downharpoonright: "⇂",
    downharpoonleft: "⇃",
    looparrowright: "↱",
    looparrowleft: "↰",
};

const operatorFunctionSymbols = {
    intercal: "⊺",
    doublebarwedge: "⩞",
    curlyvee: "⋎",
    curlywedge: "⋏",
    smallsetminus: "∖",
    divideontimes: "⋇",
    dotplus: "∔",
    bigtriangleup: "△",
    bigtriangledown: "▽",
    lhd: "◁",
    rhd: "▷",
    unlhd: "⊴",
    unrhd: "⊵",
    intop: "∫",
    smallint: "∫",
};

const spacingFunctionSymbols = {
    enspace: " ",
    quad: " ",
    qquad: "  ",
    thinspace: " ",
    medspace: " ",
    thickspace: " ",
    negthinspace: "",
    negmedspace: "",
    negthickspace: "",
    nobreakspace: " ",
    tiny: "",
    scriptsize: "",
    footnotesize: "",
    small: "",
    normalsize: "",
    large: "",
    Large: "",
    LARGE: "",
    huge: "",
    Huge: "",
};

const delimiterFunctionSymbols = {
    left: "left",
    right: "right",
    middle: "middle",
    langle: "⟨",
    rangle: "⟩",
    lfloor: "⌊",
    rfloor: "⌋",
    lceil: "⌈",
    rceil: "⌉",
    vert: "|",
    Vert: "‖",
    lvert: "|",
    rvert: "|",
    lVert: "‖",
    rVert: "‖",
    ulcorner: "⌜",
    urcorner: "⌝",
    llcorner: "⌞",
    lrcorner: "⌟",
    not: "not",
    dots: "…",
    dotsb: "⋯",
    dotsc: "…",
    dotsi: "⋯",
    dotsm: "⋯",
    dotso: "…",
    imath: "ı",
    jmath: "ȷ",
    Finv: "Ⅎ",
    Game: "⅁",
    mho: "℧",
    eth: "ð",
    prime: "′",
    backprime: "‵",
    diagup: "╱",
    diagdown: "╲",
    therefore: "∴",
    because: "∵",
    measuredangle: "∡",
    sphericalangle: "∢",
    blacktriangle: "▲",
    blacktriangledown: "▼",
    blacktriangleleft: "◀",
    blacktriangleright: "▶",
    bigstar: "★",
    circledR: "®",
    circledS: "Ⓢ",
    flat: "♭",
    natural: "♮",
    sharp: "♯",
    S: "§",
    P: "¶",
    copyright: "©",
    pounds: "£",
    yen: "¥",
    checkmark: "✓",
    maltese: "✠",
    llbracket: "⟦",
    rrbracket: "⟧",
    lgroup: "⟮",
    rgroup: "⟯",
    lmoustache: "⎰",
    rmoustache: "⎱",
    bracevert: "⎪",
    lBrace: "⦃",
    rBrace: "⦄",
};

const punctuationFunctionSymbols = {
    cdotp: "⋅",
    ldotp: ".",
    colon: ":",
};

const textFunctionSymbols = {
    AA: "Å",
    ss: "ß",
    ae: "æ",
    oe: "œ",
    AE: "Æ",
    OE: "Œ",
    o: "ø",
    O: "Ø",
    i: "ı",
    j: "ȷ",
};

const styleFunctionSymbols = {
    displaystyle: "displaystyle",
    textstyle: "textstyle",
    scriptstyle: "scriptstyle",
    scriptscriptstyle: "scriptscriptstyle",
    limits: "limits",
    nolimits: "nolimits",
};

const literalFunctionSymbols = {
    "!": "!",
    ",": ",",
    ":": ":",
    ";": ";",
    " ": " ",
    "\\": "\\",
};

export const functions = {
    ...trigonometricFunctions,
    ...logarithmicFunctions,
    ...namedLimitFunctions,
    ...algebraFunctions,
    ...directedLimitFunctions,
    ...relationFunctionSymbols,
    ...arrowFunctionSymbols,
    ...operatorFunctionSymbols,
    ...spacingFunctionSymbols,
    ...delimiterFunctionSymbols,
    ...punctuationFunctionSymbols,
    ...textFunctionSymbols,
    ...styleFunctionSymbols,
    ...literalFunctionSymbols,
};
