const lowercaseGreek = {
    alpha: "α",
    beta: "β",
    gamma: "γ",
    delta: "δ",
    epsilon: "ϵ",
    zeta: "ζ",
    eta: "η",
    theta: "θ",
    iota: "ι",
    kappa: "κ",
    lambda: "λ",
    mu: "μ",
    nu: "ν",
    xi: "ξ",
    omicron: "ο",
    pi: "π",
    rho: "ρ",
    sigma: "σ",
    tau: "τ",
    upsilon: "υ",
    phi: "ϕ",
    chi: "χ",
    psi: "ψ",
    omega: "ω",
};

const variantGreek = {
    varepsilon: "ε",
    vartheta: "ϑ",
    varkappa: "ϰ",
    varpi: "ϖ",
    varrho: "ϱ",
    varsigma: "ς",
    varphi: "φ",
    varbeta: "ϐ",
};

const uppercaseGreek = {
    Alpha: "Α",
    Beta: "Β",
    Gamma: "Γ",
    Delta: "Δ",
    Epsilon: "Ε",
    Zeta: "Ζ",
    Eta: "Η",
    Theta: "Θ",
    Iota: "Ι",
    Kappa: "Κ",
    Lambda: "Λ",
    Mu: "Μ",
    Nu: "Ν",
    Xi: "Ξ",
    Omicron: "Ο",
    Pi: "Π",
    Rho: "Ρ",
    Sigma: "Σ",
    Tau: "Τ",
    Upsilon: "Υ",
    Phi: "Φ",
    Chi: "Χ",
    Psi: "Ψ",
    Omega: "Ω",
};

const specialGreek = {
    digamma: "ϝ",
    Digamma: "Ϝ",
    varGamma: "𝛤",
    varDelta: "𝛥",
    varTheta: "𝛩",
    varLambda: "𝛬",
    varXi: "𝛯",
    varPi: "𝛱",
    varSigma: "𝛴",
    varUpsilon: "𝛶",
    varPhi: "𝛷",
    varPsi: "𝛹",
    varOmega: "𝛺",
};

export const greek = {
    ...lowercaseGreek,
    ...variantGreek,
    ...uppercaseGreek,
    ...specialGreek,
};
